### ISSUE TITLE
Null is not an object (evaluating '_nativeInterface.default.getPhotos')

### ISSUE THREAD

**Issue by dantonio1401** [react-native-community/react-native-cameraroll#112]
# Question

I am getting an error when using the CameraRoll library stating that the object is Null

I see that this question has been asked before with different versions of react-native. I have tried the solutions outlined in those discussions (auto linking/ manually linking) and nothing has worked

Here is the system information:
```System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Memory: 249.40 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 1.5 AI-141.2456560
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.43.4```

Any assistance would be helpful thanks!

**Comment by bartolkaruza** [comment]
Hey there, so how are you linking right now? I'm going to need a bit more context. The error means the following: You are accessing a native module, that is not actually there in the app binary. This means, for whatever reason, the library did not get included in the iOS build. I can't help you with tech support directly, but what usually works for me is the following:
1) init a new project
2) add the cameraroll library to the new project using autolinking only
3) add your js code specific to the cameraroll in that new project and confirm that it works (by calling getPhotos or just use the example from the docs)

Now you have a working project to compare your own project to. The reason why your actual project doesn't work is going to be in the diff between the generated project and your actual project.

If you do the above steps and you find that the library still doesn't work, then please share that newly created project with me and I'll reopen this ticket.
