### ISSUE TITLE
While loading the imges of library it get flickering whole images

### ISSUE THREAD

**Issue by nihp** [react-native-community/react-native-cameraroll#119]
While loading the images from the Library.

First it gets flickering whole images while loading and shows all the images
Second time it shows only some images and failed to load all the images

**Comment by bartolkaruza** [comment]
@nihp this issue will need a lot more context for us to be able to help you

**Comment by bartolkaruza** [comment]
I'm closing this for now as it's likely an implementation issue on the app side, but I'm happy to reopen if more information is provided indicating a library bug.
