### ISSUE TITLE
CameraRoll doesn't return the extension of the uploaded file

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-cameraroll#12]
* * *
  This issue was originally created by @truongluong1314520 as facebook/react-native#24026.
  * * *

  ## 💥 Regression Report

CameraRoll doesn't return currently taken image and video.
CameraRoll returns type only specific `image` or `video`. How can I know the extension of the file? I really need that one.

## Last working version

CameraRoll returns currently taken image and video.
CameraRoll returns type: image/png or video/mp4 instead of just image or video

Worked up to version:

Worked version is 0.57.4

Stopped working in version:

React native version 0.59.1

## To Reproduce

1/ Use `react-native-image-picker` to launch default camera and take a picture
2/ Use CameraRoll to load 1 image and it load the image from long time ago, not the currently taken

## Expected Behavior

Can you please take a look and add return extension for both images and videos just like it does before?

CameraRoll should return the currently taken image. Or if there is anyway to force it to do so?

## Code Example

    CameraRoll.getPhotos({

        first: 1,
        assetType: 'All',
        groupTypes: 'All',

    }).then((result) => {

        // DOES NOT return the currently taken image or video
        
        // The type of returned file is only 'image' ot 'video'

    }).catch((error) => {

        console.log("loadOneMedia error", error);
    });

## Environment

info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
      Memory: 1.07 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: android-18 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by truongluong1314520** [comment]
Hi @cpojer , will react-native-community be responsible for CameraRoll now like NetInfo and AsyncStorage? Please let me know so I can post the issues in correct place and you don't have to spend time moving the issues 😃

**Comment by cpojer** [comment]
@truongluong1314520 yes!

**Comment by bartolkaruza** [comment]
@truongluong1314520 I'm seeing two separate issues here; 1) the image information has changed and 2) the returned image is not the latest added image to cameraroll. Could you help us out by opening another separate issue for 2), so we can keep this issue report focused on 1) ?

With regards to the image meta info, did that change between 0.57.4 and 0.59.1 or just the return of the recently added one?

**Comment by truongluong1314520** [comment]
Hi @bartolkaruza , sorry for the late reply. I created the issue, please take a look.

**Comment by truongluong1314520** [comment]
Hi @cpojer and @bartolkaruza , I am still getting stuck at the media extension. The Camera Roll return image link like this:

    ph://99D53A1F-FEEF-40E1-8BB3-7DD55A43C8B7/L0/001

There is no media extension. Do you have any work around for this? I really need the file extension to work with it later on server

**Comment by truongluong1314520** [comment]
Hi guys, I have a work around, the returned extension is not pretty but it is useable:

From the file `RNCCameraRollManager.m`, we add these 2 lines

<img width="1027" alt="Screen Shot 2019-04-24 at 3 00 45 PM" src="https://user-images.githubusercontent.com/32918401/56642591-fc4a3400-66a1-11e9-80d9-6defdc13dece.png">

and 

<img width="670" alt="Screen Shot 2019-04-24 at 3 03 21 PM" src="https://user-images.githubusercontent.com/32918401/56642655-1edc4d00-66a2-11e9-8741-69f7f8e8765c.png">

Now you have the extension.

**Comment by truongluong1314520** [comment]
Hi @cpojer , can you please close this issue. Thank you 😃

**Comment by sperezm97** [comment]
hi everyone, keep persist :( using `react-native-camera` to taking photos and `react-native-cameraroll` to save them. it does not bring me the latest photo taking. Only happen on Android 7.0+, my `react-native-version` is v0.60.5. Let me know if are something new.

**Comment by mishsom** [comment]
@bartolkaruza why is this issue closed, it's still a problem with camera roll, we do not get extension or mime type information for assets on ios.

**Comment by mishsom** [comment]
@LuongTruong can we clean your solution and make it part of the library? What do you mean by not pretty but usable?
