### ISSUE TITLE
Where is CHANGELOG.md?

### ISSUE THREAD

**Issue by thekevinbrown** [react-native-community/react-native-cameraroll#131]
# Question

The Pull Request template mentions that we should update this file. Does it still exist?

If so: Where is it?
If not: Could we update the PR template to not mention this?

**Comment by bartolkaruza** [comment]
So the source of this issue is that the project uses react-native-community wide templates https://github.com/react-native-community/.github/tree/master/.github , which we shouldn't edit directly. I'll make a local PR template which removes that line.

**Comment by thekevinbrown** [comment]
Thanks!
