### ISSUE TITLE
[Android] Re-open Use DCIM direcotry for saveToCameraRoll #94

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/react-native-cameraroll#141]
@FrikkieSnyman I opened this issue so we don't loose track of the changes you made in #94

**Comment by dokkis** [comment]
@bartolkaruza I read couple of issues and several complains that might be related to this. Do you know why the change was made in the first place and which device affects? Does it make sense having a parameter for Android only, e.g. useDCIMFolder as workaround?

**Comment by bartolkaruza** [comment]
The change was reverted (temporarily) because the open question is if the saving to album still works in combination with the DCIM change. If we can confirm that saving to album still works as expected, then we can save to DCIM by default (without a flag). Do you have a spare cycle to test this?

**Comment by dokkis** [comment]
@bartolkaruza I see if I can take a look tomorrow. In case we need the current folders to save in album, then eventually does it make sense use DCIM if no album is provided? Trying to get options upfront so I can eventually raise a PR depending on results of testing.

**Comment by bartolkaruza** [comment]
In case it breaks some existing functionality, then a useDCIMFolder flag might be a good idea. For advanced tuning users can turn that on/off based on the device details to try and resolve those crashes. They would have to handle the no-album situation as needed in their apps. How does that sound?

**Comment by dokkis** [comment]
@bartolkaruza I try out few things.

Problem #1:
First of all there is a bug in the current handling of `type` param for Android in the save function. From doc it's either `video` or `photo`, but on implementation https://github.com/react-native-community/react-native-cameraroll/blob/master/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L133 it's checking over `mov` value. If I try to pass `mov` as value from JS, I got an error on the enum check. So there is no way to reach the current `Environment.DIRECTORY_MOVIES` dir in Android.

Problem #2:
If I try to simply replace Environment.DIRECTORY_PICTURES with Environment.DIRECTORY_DCIM, the save photo works (no errors) but I never see the new album appearing in the Photos app.

Potential problem #3:
Not sure if this is really a problem, but if you save without specifying an album, your media will go into Pictures "album" not into Camera, as opposed if you use DCIM that makes your media ppearing to camera. This might be a `regression` compared to the old saveToCameraRoll function.

Given all the above consideration, my recommendation would be: 
1. fix #1 by changing mov with video as value in code, so we can reach that if branch
2. combining #2 and #3 by using DIRECTORY_DCIM if you don't provide any album, so your photo really goes into the `Camera roll`. Is `Camera roll` supposed to be the Camera album? If yes, I think this is more appropriate for this function. And we can keep Environment.DIRECTORY_MOVIES and Environment.DIRECTORY_PICTURES if you need to save things into an Album.

**Comment by dokkis** [comment]
there is an additional problem, and doc is not correct:

`If the tag has a file extension of .mov or .mp4, it will be inferred as a video. Otherwise it will be treated as a photo. To override the automatic choice, you can pass an optional type parameter that must be one of 'photo' or 'video'.`

This is not true (at least for Android), it's inferred just looking at `type` param passed. So if you provide a video without a type, it will be saved into pictures.

**Comment by bartolkaruza** [comment]
Thanks @dokkis, great analysis! With regards to the open Redmi device I hope this will resolve it for those apps that don't use albums. I don't have a Redmi device, so it's a bit harder to test.

**Comment by dokkis** [comment]
@bartolkaruza yeah I also don't have a Redmi to replicate, but looking at the above analysis it sounds a reasonable implementation, at least we bring the old implementation that saveToCameraRoll used to have before the album concept was introduced.
