### ISSUE TITLE
#import <React/RCTBridge.h>——'React/RCTBridge.h' file not found

### ISSUE THREAD

**Issue by legendforfree** [react-native-community/react-native-cameraroll#142]
I have a problem with `react-native-cameraroll`,when i try flow these step,this error log happend.
## step

1. In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
2. Go to node_modules ➜ @react-native-community/cameraroll and add RNCCameraroll.xcodeproj
3. In XCode, in the project navigator, select your project. Add libRNCCameraroll.a to your project's Build Phases ➜ Link Binary With Libraries
4. Run your project (Cmd+R)<

![1&2.step](https://user-images.githubusercontent.com/46747508/74121841-23a7c880-4c04-11ea-8f17-805b48b7e167.png)
![3.step](https://user-images.githubusercontent.com/46747508/74121906-56ea5780-4c04-11ea-9bac-386e682c8759.png)

im not sure there is I did wrong in Xcode or its wrong by `react-native-cameraroll `.i wish someone can give me some advise,that will give me a big help.
## pod file
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ym123' do
  # Pods for ym123
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'ym123Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'ym123-tvOS' do
  # Pods for ym123-tvOS

  target 'ym123-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
  if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
   end
  end
 end
end

```
##  package.json
```
{
  "name": "ym123",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/cameraroll": "^1.4.1",
    "@react-native-community/masked-view": "^0.1.6",
    "dva-core": "^2.0.2",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-dom": "^16.12.0",
    "react-native": "0.61.5",
    "react-native-general-actionsheet": "^1.0.4",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-image-zoom-viewer": "^2.2.27",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.2",
    "react-native-safe-area-view": "^1.0.0",
    "react-native-screens": "^2.0.0-beta.2",
    "react-native-smart-tip": "^2.0.1",
    "react-native-swiper": "^1.5.14",
    "react-native-unimodules": "^0.7.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.1.1",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-navigation-stack": "^2.1.1",
    "react-navigation-tabs": "^2.7.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "babel-preset-react-app": "^9.1.1",
    "eslint": "^6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.9.0"
  },
  "babel": {
    "plugins": [
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ]
    ],
    "presets": [
      "react-app"
    ]
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by liuche692326532** [comment]
Same as mine

**Comment by legendforfree** [comment]
> Same as mine

its seems a common problem with `react-native-cameraroll`,i was stuck in here all day

**Comment by Peretz30** [comment]
any updates?

**Comment by legendforfree** [comment]
> any updates? v1.2.1 works fine

its a new project,use "@react-native-community/cameraroll": "^1.4.1",i will retry 1.2.1.thanks

**Comment by legendforfree** [comment]
the problem is solved,its wrong about this
![image](https://user-images.githubusercontent.com/46747508/74620068-cadfaf00-5172-11ea-8888-1a2dd5b29b05.png)
libRNCCameraroll.a
---
when i see react-native-cameraroll teach class in youtube,i notice its a wrong link
![image](https://user-images.githubusercontent.com/46747508/74620179-3033a000-5173-11ea-90eb-4452b75d7e78.png)
its should link libreact-native-cameraroll.a.
---
i have to shut down this issue,thanks all you guys

**Comment by ceo-epiclions** [comment]
> ## the problem is solved,its wrong about this
> ![image](https://user-images.githubusercontent.com/46747508/74620068-cadfaf00-5172-11ea-8888-1a2dd5b29b05.png)
> libRNCCameraroll.a
> when i see react-native-cameraroll teach class in youtube,i notice libRNCCameraroll.a its a wrong link,its should link libreact-native-cameraroll.a.
> ![image](https://user-images.githubusercontent.com/46747508/74620179-3033a000-5173-11ea-90eb-4452b75d7e78.png)
> 
> my project working now ,i have to shut down this issue,thanks all you guys

This works fine. (RN v.0.61.5)
 Please fix the README.md file to prevent further pain to others (I've spent for 3 hours for this...)

**Comment by ivan-jorge001** [comment]
I cant find the file libreact-native-cameraroll.a

**Comment by giacomoalonzi** [comment]
Where is the  libreact-native-cameraroll.a file?

**Comment by ceo-epiclions** [comment]
> Can you guys explain further how you solved this, I cant find the file libreact-native-cameraroll.a

> Where is the libreact-native-cameraroll.a file?

@giacomoalonzi @ivan-jorge001 Did you run 'pod install' in ios folder?

**Comment by huyhai** [comment]
Where is the libreact-native-cameraroll.a file?

manual install

**Comment by Jaeyeon2** [comment]
> > ## the problem is solved,its wrong about this
> > ![image](https://user-images.githubusercontent.com/46747508/74620068-cadfaf00-5172-11ea-8888-1a2dd5b29b05.png)
> > libRNCCameraroll.a
> > when i see react-native-cameraroll teach class in youtube,i notice libRNCCameraroll.a its a wrong link,its should link libreact-native-cameraroll.a.
> > ![image](https://user-images.githubusercontent.com/46747508/74620179-3033a000-5173-11ea-90eb-4452b75d7e78.png)
> > my project working now ,i have to shut down this issue,thanks all you guys
> 
> This works fine. (RN v.0.61.5)
> Please fix the README.md file to prevent further pain to others (I've spent for 3 hours for this...)

thank you! i solved problem

**Comment by nhohb** [comment]
> Where is the libreact-native-cameraroll.a file?
> 
> manual install

You should run `npx pod-install` first, it looks like this
![image](https://user-images.githubusercontent.com/48668114/89874775-81829080-dbe6-11ea-9e0c-7092ceacbdae.png)

**Comment by cae-li** [comment]
Mine looked like this - clicked on 'react-native-cameraroll' and it worked for me.

![Screenshot 2023-02-21 at 12 33 17](https://user-images.githubusercontent.com/104053427/220248532-e5e5694f-fd51-4d3e-a1bf-a90d1db3ce60.png)
