### ISSUE TITLE
Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.) iOS

### ISSUE THREAD

**Issue by alfayez91** [react-native-community/react-native-cameraroll#143]
# Question
I am trying to store images which is getting from link to Gallery.

**code:** 
`
let image = 'https://i.picsum.photos/id/190/200/300.jpg'
CameraRoll.saveToCameraRoll(image, 'photo').then(r => {
            Alert.alert('alert', 'saved successfully .', [{ text: 'okay'}]);
        })
        .catch((err) => {
            console.log(err);
            Alert.alert('error', ' error '+ err, [{ text: 'okay'}]);
        })
`

**Error:**

Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)

**Comment by ramon90** [comment]
Same issue

**Comment by Petagorus** [comment]
Same issue

**Comment by a289459798** [comment]
Same issue

**Comment by yannicklaclau** [comment]
same issue - roll back to 1.4.0 fixed it, as @Petagorus suggested

**Comment by hcygit** [comment]
same issue and rollback to 1.4.0 works

**Comment by izzykreie** [comment]
@hcygit version 1.4 of what?

**Comment by izzykreie** [comment]
@yannicklaclau how do I roll back to 1.4 of a library?

**Comment by Peretz30** [comment]
@izzykreie `yarn upgrade @react-native-community/cameraroll@1.4.0`

**Comment by ahsanihsan** [comment]
I am still getting this issue on 1.4.0 

Any update?

**Comment by wuhuanda** [comment]
Same issue. No one manage the issue?

**Comment by tronin** [comment]
The same problem with 1.5.2

**Comment by anthonykrivonos** [comment]
Can confirm with @tronin. Only got image saving to work via the following solution

> @izzykreie `yarn upgrade @react-native-community/cameraroll@1.4.0`

**Comment by djGrill** [comment]
> Same issue >> i resolve issue by version 1.4.0

This solve this issue for me on:
- `"react-native": "0.60.6"`

Though this was also necessary: https://github.com/react-native-community/react-native-cameraroll/issues/147#issuecomment-602512409

**Comment by bartolkaruza** [comment]
Does anyone have time to help and make a PR with a fix for this issue? There appears to be a solution at https://github.com/react-native-community/react-native-cameraroll/issues/159#issue-588866924 . I'm happy to review and merge a well tested PR. Cheers

**Comment by marcoskoch** [comment]
> Does anyone have time to help and make a PR with a fix for this issue? There appears to be a solution at [#159 (comment)](https://github.com/react-native-community/react-native-cameraroll/issues/159#issue-588866924) . I'm happy to review and merge a well tested PR. Cheers

PR with adjustment @bartolkaruza

**Comment by AnurajDev** [comment]
If this helps someone,

I got the same error in the React Native Cameraroll version 4.1.2. (iOS)

"react-native": "0.63.3".

I solved the issue by **prefixing "file://" in the image path for saveToCameraRoll** method.

**Comment by jake920220** [comment]
@AnurajDev Hi there, What do you mean prefixing "file://" in the image path?
Do you mean save(`file://${url}`) using like this?

**Comment by AnurajDev** [comment]
@jake920220 Sorry, its been a year and I completely lost the context. But from what I remember, I think prefixing "file://" means the same thing that you mentioned file://${url} . The image path should be prefixed with "file://".

**Comment by jake920220** [comment]
> @jake920220 Sorry, its been a year and I completely lost the context. But from what I remember, I think prefixing "file://" means the same thing that you mentioned file://${url} . The image path should be prefixed with "file://".

Thanks for replying , It doesn't seem to work for me but really appreciate for your comment.
