### ISSUE TITLE
React/RCTImageLoaderProtocol.h' file not found

### ISSUE THREAD

**Issue by 1280103995** [react-native-community/react-native-cameraroll#144]
<img width="590" alt="2020-02-19 17 09 05" src="https://user-images.githubusercontent.com/17424486/74819140-e990a200-533a-11ea-8413-d3a8d40136f0.png">

**I got this error when I build using xcode**

```
"@react-native-community/cameraroll": "^1.4.1",
"react": "16.8.6",
"react-native": "0.59.9",
```

Version 1.3.0 doesn't work either

**Comment by 1280103995** [comment]
I fixed it. 
First execute ```unlink```, then delete ```RNCCameraroll.xcodeproj``` in ```Libraries```, delete ```libRNCCameraroll.a``` in ```Link Binary With Libraries```, and finally Manual installation. 
Tip: If ```RNCameraroll.xcodeproj```exists, also delete it.

**Comment by matthewadel** [comment]
Changing
#import <React/RCTImageLoaderProtocol.h>
to
#import <React/RCTImageLoader.h>
fixed the build issue for me

Don't forget to clean your DerivedData folder

**Comment by kigh143** [comment]
Hello @matthewadel i am stil getting this error what have i done wrongly.
