### ISSUE TITLE
Failed to build with RN 0.64 'React/RCTImageLoaderProtocol.h' file not found

### ISSUE THREAD

**Issue by xcniao** [react-native-community/react-native-cameraroll#147]
Failed to build with RN 0.64 'React/RCTImageLoaderProtocol.h' file not found
 "@react-native-community/cameraroll": "^1.4.1",

**Comment by baotoan1905** [comment]
How to fix it ? I got same issue

**Comment by truong12** [comment]
@baotoan1905 you can remove `#import <React/RCTImageLoaderProtocol.h>` in `node_modules/@react-native-community/cameraroll/ios/RNCCameraRollManager.m`

**Comment by matthewadel** [comment]
Changing
#import <React/RCTImageLoaderProtocol.h>
to
#import <React/RCTImageLoader.h>
fixed the build issue for me

**Comment by marlti7** [comment]
same problem in rn 0.59.9

**Comment by marlti7** [comment]
> Changing
> #import <React/RCTImageLoaderProtocol.h>
> to
> #import <React/RCTImageLoader.h>
> fixed the build issue for me

not work for me in rn 0.59.9

**Comment by djGrill** [comment]
> Changing
> #import <React/RCTImageLoaderProtocol.h>
> to
> #import <React/RCTImageLoader.h>
> fixed the build issue for me

This solve this issue for me on:
- `"react-native": "0.60.6"`
- `@react-native-community/cameraroll": "1.4.0"`

The reason for using `1.4.0` is because of the `PHPhotosErrorDomain error -1` issue:
#143
#157

**Comment by TristanH** [comment]
I was having this issue in 1.5.2 -- downgrading to 1.4.0 worked for me!
