### ISSUE TITLE
CameraRoll returns photos if assetType is equal to "Videos"

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-cameraroll#15]
* * *
  This issue was originally created by @indapublic as facebook/react-native#22341.
  * * *

  
  - [ x] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 29.58 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I receive photos in iOS app, despite the fact that I set assetType: 'Videos'

## Reproducible Demo
```
const defaultParams: GetPhotosParamType = {
    first: 6,
    groupTypes: 'All',
    after: undefined,
};
Promise.all([
    CameraRoll.getPhotos({
    ...defaultParams,
    assetType: 'Photos',
    }),
    CameraRoll.getPhotos({
    ...defaultParams,
    assetType: 'Videos',
    })
]).then(results => {
    console.warn(results[0]);
    console.warn(results[1]);
    console.warn(results[0].edges[0].node.image.uri === results[1].edges[0].node.image.uri);
});
```

![screen shot 2018-11-19 at 16 36 08](https://user-images.githubusercontent.com/856260/48690189-3e65da00-ec19-11e8-8d1e-b606cc7d86be.png)

**Comment by joseguerrerov** [comment]
@indapublic first, the error is very weird, can you try using `assetType: All` just to check it returns any video. Second, It seems you're on __0.57.5__ and in that version the iOS cameraRoll implementation was using `ALAssetsLibrary`(deprecated) and now the __react-native-community/react-native-cameraRoll__ and the latest __CameraRoll__ from __0.59__ uses `PhotoKit`.

Using the latest release from this repo in 0.5 works as expected, might worth the upgrade 🤔

**Comment by assaqqaf** [comment]
@joseguerrerov  The new URI schema returned by `PhotoKit` (e.g: ph://....). Cause A problem with Image component.

```<Image source={{ uri: 'ph://fsdE.....' }} />```

Any idea of how to handle this situation?

**Comment by joseguerrerov** [comment]
@assaqqaf which version of RN ?, can you run `react-native info` On `0.59 >` Im not having issues.

**Comment by assaqqaf** [comment]
@joseguerrerov Thank you for a response. Actually, it happens with video. 

`react-native info` output:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 7.51 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.59.1
```

Example code:
```
import React, {Component} from 'react';
import {Image, FlatList} from 'react-native';
import CameraRoll from "@react-native-community/cameraroll";

export default class App extends Component {
  state = {
    images: [],
  };

  componentDidMount() {
    CameraRoll.getPhotos({
      first: 10,
      groupTypes: "All",
      assetType: "Videos",
    })
    .then((data) => this.setState({ images: data.edges }));
  }

  render() {
    return (
      <FlatList
        data={this.state.images}
        renderItem={({item}) => (
            <Image
              style={{width: 50, height: 50}}
              source={{uri: item.node.image.uri}}
            />
        )}
      />
    );
  }
}
```

Before `PhotoKit` the above code was working. But now it triggers an error.

<img width="898" alt="Screenshot 2019-04-11 at 10 14 06 AM" src="https://user-images.githubusercontent.com/1142577/55926108-a063c200-5c42-11e9-978d-4e23c41f6929.png">

**Comment by gbxnga** [comment]
> @joseguerrerov The new URI schema returned by `PhotoKit` (e.g: ph://....). Cause A problem with Image component.
> 
> `<Image source={{ uri: 'ph://fsdE.....' }} />`
> 
> Any idea of how to handle this situation?

I'm haveing the same problem. uri was starting with `file://`, now it returns `ph://` which causes an error in my code

**Comment by ZackLeonardo** [comment]
same problem with new "ph://"

**Comment by issacnitin** [comment]
Any workarounds to get file:// back ?

**Comment by Abdelrahman-Nabil** [comment]
having the same issue with ph:// when using imageManipulator.manipulateAsync on iOS and passing a ph:// path.

**Comment by EdmundMai** [comment]
Same issue here
```

    CameraRoll.getPhotos({
      first: 1,
      groupTypes: "Library",
      assetType: "Photos",
    })
      .then(({ edges }) => {
        const [edge] = edges;
        const {
          node: { image },
        } = edge;
        console.log("xxxxxxxxxxxxx: ", image.uri); // PRINTS: xxxxxxxxxxxxx:  ph://96F3704A-D84C-44D7-ADF4-F1455D05CAED/L0/001
        setLatestPhotoUrl(image.uri);
      })
      .catch(err => {
        console.log("gallery", err);
      });

```

**Comment by jzyds** [comment]
> Any workarounds to get file:// back ?

https://github.com/jzyds/react-native-convert-ph-asset

**Comment by GreatFan** [comment]
if([path hasPrefix:@"ph://"]){
      
      NSString *assetID = [path substringFromIndex:@"ph://".length];
      PHFetchResult *results = [PHAsset fetchAssetsWithLocalIdentifiers:@[assetID] options:nil];
      
      PHAsset *asset = [results firstObject];
      
      PHImageRequestOptions *request = [PHImageRequestOptions new];
      request.version = PHImageRequestOptionsVersionCurrent;
      request.deliveryMode = PHImageRequestOptionsDeliveryModeHighQualityFormat;
      request.resizeMode = PHImageRequestOptionsResizeModeNone;
      request.synchronous = YES;
     
      [[PHImageManager defaultManager] requestImageDataForAsset:asset options: request resultHandler:^(NSData *imageData, NSString *dataUTI, UIImageOrientation orientation, NSDictionary *info) {
        CGImageSourceRef source = CGImageSourceCreateWithData((__bridge CFDataRef)imageData, NULL);
        if (NULL != source) {
          NSDictionary * metadataDic = (NSDictionary *)CFBridgingRelease(CGImageSourceCopyPropertiesAtIndex(source, 0, NULL));
          NSLog(@"metada:%@",metadataDic);

          CFRelease(source);

        }else{
          
          NSLog(@"CGImageSourceRef NULL");
        }
      }];
      
    }

**Comment by bartolkaruza** [comment]
The original issue is resolved as far as I can tell by simply upgrading. 

Workarounds for the PH uri's are at https://github.com/react-native-community/react-native-cameraroll/issues/52

Thank you for reporting 🙂
