### ISSUE TITLE
getAlbums is not funtion

### ISSUE THREAD

**Issue by PhuongNguyenETIT** [react-native-community/react-native-cameraroll#155]
# Bug

## Environment info

React native info output:

```bash
_cameraroll.default.getAlbums is not a function
Library version: 1.4.1
```
Library version: 1.4.1

Describe what you expected to happen:

1.
2.

## Reproducible sample code
CameraRoll.getAlbums({
      assetType: 'Photos'
    })
      .then(data => {
        console.log(data);
      })
      .catch(err => {
        console.log(err);
      });

**Comment by netdown** [comment]
The commit which adds this function is not included in the latest release (dont ask why..). You have to pull the current master branch.

**Comment by SteveTro** [comment]
@netdown 

I still get an error using getAlbums()

> TypeError: _cameraroll.default.getAlbums is not a function.(in '_cameraroll.default.getAlbums({assetType:'Photos'})','_cameraroll.default.getAlbums' is undefined)

i installed the latest version via npm

` npm install @react-native-community/cameraroll@latest
`
and also tried it directly via github

` npm install react-native-community/cameraroll
`
my package.json

`"@react-native-community/cameraroll": "^1.5.2"`

if i check the CameraRoll.js in the node_modules folder the method is also there

```
 static getAlbums(
    params?: GetAlbumsParams = {assetType: ASSET_TYPE_OPTIONS.All},
  ): Promise<Album[]> {
    return RNCCameraRoll.getAlbums(params);
  }
```

Any idea?

**Comment by netdown** [comment]
@SteveTro If you are trying on android, run a gradlew clean first. If does not work, try to remove and install the package again. It's ok for me.

Also make sure import and function call is correct:
`import CameraRoll from '@react-native-community/cameraroll';
CameraRoll.getAlbums({
	assetType: 'Photos',
}).then(res => {});`

**Comment by SteveTro** [comment]
@netdown 

i copied your code to my project and run

`npm remove @react-native-community/cameraroll && npm install @react-native-community/cameraroll && cd android && .\gradlew clean && cd .. && react-native run-android`

but the error is still there.
Its driving me crazy cause i can see the native code in node_modules but its not working

**Comment by netdown** [comment]
@SteveTro Try to link it manually. If still no success, try it with a blank project.
