### ISSUE TITLE
Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.) iOS

### ISSUE THREAD

**Issue by ahsanihsan** [react-native-community/react-native-cameraroll#157]
# Bug

`Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)
    at Object.fn [as saveToCameraRoll] (NativeModules.js:99)
    at Function.save (CameraRoll.js:163)
    at Function.saveToCameraRoll (CameraRoll.js:169)
    at _callee2$ (VM5 index.bundle:209)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170`

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 60.19 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /var/folders/7n/tg8wdbns7yvg3wqwnh_mzmp40000gn/T/yarn--1585096434645-0.8370493466760465/node
    Yarn: 1.22.1 - /var/folders/7n/tg8wdbns7yvg3wqwnh_mzmp40000gn/T/yarn--1585096434645-0.8370493466760465/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 1.4.0

## Steps To Reproduce
1. I am just calling the CameraRoll.saveToCameraRoll with the remote url
...

Describe what you expected to happen:

1. I expected the video to be saved in the photos
2. I even tried it on the latest version and its still the same

## Reproducible sample code

```
CameraRoll.saveToCameraRoll(url, 'video')
        .then(response => {
          console.log('***RES**');
          console.log(response);
          console.log('***RES**');
          this.setState({isDownloading: false});
          this.refs.completionToast.show('Download completed!');
        })
        .catch(error => {
          console.log('*****');
          console.log(error);
          console.log('*****');
          this.setState({isDownloading: false});
          this.refs.completionToast.show(
            'There was a problem downloading the video, please try again later',
          );
        });
```

**Comment by SteveTro** [comment]
Did you have all the nessesary permissions in the Podfile and in your Info.plist?
I had that error a few times ago and i think i remeber that it was a permission problem

**Comment by HicoderDR** [comment]
same problem

**Comment by roshan-p** [comment]
same error

**Comment by HicoderDR** [comment]
I solved it by roll back to version 1.4.0.
**yarn upgrade @react-native-community/cameraroll@1.4.0**

**Comment by roshan-p** [comment]
> I solved it by roll back to version 1.4.0.
> **yarn upgrade @react-native-community/cameraroll@1.4.0**

thanks it's work

**Comment by zhaochongyang01** [comment]
Hello, I set the version to 1.4.0 according to your solution, but it still cannot be used after testing. My react-native version is 0.62.0. What was your successful react-native version?

**Comment by HicoderDR** [comment]
> Hello, I set the version to 1.4.0 according to your solution, but it still cannot be used after testing. My react-native version is 0.62.0. What was your successful react-native version?

"react-native":"0.61.4"

**Comment by djGrill** [comment]
> I solved it by roll back to version 1.4.0.
> **yarn upgrade @react-native-community/cameraroll@1.4.0**

This solve this issue for me on:
- `"react-native": "0.60.6"`

Though this was also necessary: https://github.com/react-native-community/react-native-cameraroll/issues/147#issuecomment-602512409

**Comment by TristanH** [comment]
I was having this issue in 1.5.2 -- downgrading to 1.4.0 by itself worked for me!

**Comment by maks-harakhovich** [comment]
The same issue on 1.5.2, downgraded to 1.4.0.

**Comment by taschik** [comment]
This issue still persists. The only way to solve it, is to downgrade to 1.4.0.

**Comment by bartolkaruza** [comment]
Closing as duplicate of #143

**Comment by bartolkaruza** [comment]
Does anyone have time to help and make a PR with a fix for this issue? There appears to be a solution at #159 (comment) . I'm happy to review and merge a well tested PR. Cheers

**Comment by ShotSkydiver** [comment]
> Does anyone have time to help and make a PR with a fix for this issue? There appears to be a solution at #159 (comment) . I'm happy to review and merge a well tested PR. Cheers

I just opened a new PR #172  with the fixes! Works perfectly for me!

**Comment by barak109** [comment]
@bartolkaruza Still happen to me 
 "@react-native-community/cameraroll": "^4.0.0",

**Comment by chj-damon** [comment]
still happen to me. "@react-native-community/cameraroll": "^4.0.0",

**Comment by moh3n9595** [comment]
still happen to me. "@react-native-community/cameraroll": "^4.0.0"

**Comment by Marciomacdev** [comment]
still happen to me. "@react-native-community/cameraroll": "^4.0.0"

**Comment by weblancaster** [comment]
I'm also seeing the same issue.

I'm on react-native `0.63.2` and react-native-cameraroll `4.0.0` I tried a couple of things like downgrading 3 versions or so of react-native-cameraroll. I also tried on react-native `0.61.5` and react-native-cameraroll `4.0.0`.

I don't think I tried 1.4 though so I will try that now, and report back.

**Comment by weblancaster** [comment]
I got it working also using react-native `0.63.2`, react-native-cameraroll `1.4.0` and rn-fetch-blob `0.12.0`

Here is a sample code:
```
const handleDownloadVideo = async () => {
    const ext = getExtFromUrl(video);

    try {
      const file = await RNFetchBlob.config({
        fileCache: true,
        appendExt: ext,
      }).fetch('GET', video, {type: 'video'});
      const path = file.path();

      await CameraRoll.saveToCameraRoll(path, 'video');

      file.flush();
    } catch (error) {
      console.log(error);
    }
  };
```

**Comment by ashirkhan94** [comment]
Hi same issue for me
Any update?
