### ISSUE TITLE
Error Domain=PHPhotosErrorDomain Code=-1 "(null)"

### ISSUE THREAD

**Issue by billxie1988** [react-native-community/react-native-cameraroll#159]
- the code below will cause error on iOS 13 devices when import uri is https://xxxxx.png

```assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImageAtFileURL:inputURI];```

- this way works well

```
NSData *data = [NSData dataWithContentsOfURL:inputURI];
UIImage *image = [UIImage imageWithData:data];
assetRequest = [PHAssetChangeRequest creationRequestForAssetFromImage:image];
```

**Comment by bartolkaruza** [comment]
Thank you for posting the working code! Closing this as duplicate of #157
