### ISSUE TITLE
Unable to build app - Variable inputImage not used

### ISSUE THREAD

**Issue by enisinanaj** [react-native-community/react-native-cameraroll#162]
# Bug

The app cannot be built when the library is linked manually to it.
The error is:

> **Variable is unused.**

Referring to the variable `inputImage` in RNCCameraRollManager:saveToCameraRoll

```
__block UIImage *inputImage = nil;
```

## Environment info

```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 20.43 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
    npm: 5.3.0 - ~/.nvm/versions/node/v8.3.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7
    react-native: 0.61.2
```

Library version: `"@react-native-community/cameraroll": "^1.5.2"`

## Steps To Reproduce

1. Link the library manually
2. Add the path to search for the headers in
3. Run the app on the device with CMD + R
4. The app doesn't run and build failure happens

Describe what you expected to happen:

1. The app would build correctly and run on the iOS device

## Reproducible sample code

N/A

**Comment by pribeh** [comment]
Same here.

**Comment by enisinanaj** [comment]
It’s enough to comment out the variable. Check out my pr

**Comment by hzz780** [comment]
For me， i meet the same issue.
RN 0.59.10

**Comment by TuJobs** [comment]
delete it! working with me.

**Comment by MrAlekhin** [comment]
the same? should I just downgrade the camera-roll version?

**Comment by enisinanaj** [comment]
https://github.com/react-native-community/react-native-cameraroll/issues/162#issuecomment-612113183

check this out. it builds afterwards

**Comment by enisinanaj** [comment]
@MrAlekhin or get this patch here https://github.com/react-native-community/react-native-cameraroll/pull/163

**Comment by bartolkaruza** [comment]
Hey, this should be fixed in the lastest release. Please upgrade, let me know if it's still an issue, I'll reopen.
