### ISSUE TITLE
Camera Roll not returning any photos on iOS

### ISSUE THREAD

**Issue by BenJeau** [react-native-community/react-native-cameraroll#18]
I reported this bug in the react-native repo here at [facebook/react-native#24140](https://github.com/facebook/react-native/issues/24140) , but they said to post it here.

## 🐛 Bug Report
When fetching photos from the Camera Roll on **iOS** by calling `CameraRoll.getPhotos()`, it always return an empty array of edges in the data. This problem is not present when I run it on Android nor in a Snack. I tried implementing the [community version](https://github.com/react-native-community/react-native-cameraroll) and the [built-in version](https://facebook.github.io/react-native/docs/cameraroll) of the Camera Roll, but the problem persisted. I also tried running it on the iOS simulator, on an iPhone, and an iPad with no success.

## To Reproduce

1. Create a new react native project (with `react-native init`)
2.  Link the Camera Roll library
  a. With the RCTCameraRoll library as described [here](https://facebook.github.io/react-native/docs/cameraroll) from facebook's website
  b. Or with the RNCCameraRoll library as described in your README
3. Add the permission keys in the Info.plist as described [here](https://facebook.github.io/react-native/docs/cameraroll#permissions) from facebook's website
4. Copy paste the [sample code](https://facebook.github.io/react-native/docs/cameraroll#example) from facebook's website
5. Run `react-native start --reset-cache` (Solved the problems I was having with metro)
5. Run `react-native run-ios`

## Expected Behavior

I would expect the Camera Roll getPhotos function to return a populated edges array in the edges with the information/URI of images in the phones camera roll.

## Code Example

Cannot replicate bug in a [Snack](https://snack.expo.io/@benjeau/react-native-camera-roll-ios-issue).

**With the built-in Camera Roll**
Here is a [repo](https://github.com/BenJeau/reactNativeCameraRollIssue/tree/1919797c473e93c37f56ee1af79ca52dc361553d) with the code example. I also uploaded the iOS release app file to [appetize.io](https://appetize.io/app/xcva0fr6xhqtyt1yvt1jywy61g), which does have the problem. 

**With the community version**
Here is a [repo](https://github.com/BenJeau/reactNativeCameraRollIssue/tree/a54275c2283e627dd83d94c338a621349e8cb311) with the code example. I also uploaded the iOS release app file to [appetize.io](https://appetize.io/app/z6je8vmbc6um2d7cd5y46wd188), which does have the same problem.

## Environment
Output of the `react-native info` command

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 18.59 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28
        Build Tools: 21.1.2, 23.0.3, 25.0.2, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by bartolkaruza** [comment]
Thanks for reporting! I confirmed that there is a different set coming back, between older version of CameraRoll and the latest from RN core and the latest from RNC. There are images coming back for my device though, but it is a different set so I'm looking into this at priority.

I suspect it has something to do with one of the last fixes synched over from react native core https://github.com/react-native-community/react-native-cameraroll/commit/bc557cf1693ed40b9924e19bd6206255f1dcffcf

@JoshuaGross could you help us out with the reasoning behind PHAssetCollectionSubtypeSmartAlbumUserLibrary VS the original PHAssetCollectionSubtypeAny ?

**Comment by JoshuaGross** [comment]
Hi @bartolkaruza - bc557cf mentions that if `PHAssetCollectionSubtypeAny` is used, `CameraRoll.getPhotos` never gets to the end of the list of photos: no matter how far you paginate, there are always more photos, and it starts looping (we see the same IDs repeatedly). I'm not entirely sure why there was an infinite loop, though. Switching to `PHAssetCollectionSubtypeSmartAlbumUserLibrary` solved that problem and the returned photos seemed more correct; they seem to match iPhoto's "all photos" view, whereas `PHAssetCollectionSubtypeAny` didn't.

**Comment by JoshuaGross** [comment]
In my testing it wasn't entirely obvious to me that it's *possible* for us to return the *exact* same set of photos as in the past (between `PHAssetLibrary` and `ALAssetLibrary`, a lot changed). But I don't understand what would cause *no* data to be returned and I've never seen that in our many uses within Facebook, so any more information to reproduce would be helpful.

**Comment by BenJeau** [comment]
What kind of information would be useful to reproduce the problem, apart from the info from the initial post? If you guys can't reproduce it, I suppose it's a problem on my end, would you have any suggestion if it comes to that? (I've already cleared the cache of npm and yarn)

**Comment by scarlac** [comment]
@JoshuaGross After reverting that linked change I still get no photos at all. No errors, no warnings, no photos. Do we have any other clues as to where to look for a workaround? I have an app that I want to upgrade to v0.59 but I can't because of this issue.

**Comment by scarlac** [comment]
**Found solution:**
After poking around in the native code - RN 0.59.0 contains a breaking change:
You are now required to supply the `groupTypes: "All"` option when calling `getPhotos` like so:
```
CameraRoll.getPhotos({
  groupTypes: 'All', // undocumented requirement or results will be empty
  ...
})
```
If you omit `groupTypes`, a predicate (filter) will be applied such that no photos will be returned in some cases. It's possible this filter will show some photos but not all. This issue applies to both community version and RN bundled version of CameraRoll.

@JoshuaGross Could we default `groupTypes` to `'All'` by default?

**Comment by JoshuaGross** [comment]
@BenJeau Does @scarlac's suggestion solve the problem for you?

@scarlac I would prefer a documentation change if it's a documentation problem. I have a concern that changing the default to `all` will fix the case where you want all photos, and break cases where you might want to filter to specific photos. 

For what it's worth, this is the code in iOS that uses the flag. It may be worth revisiting this, but nothing sticks out to me as being problematic:
https://github.com/react-native-community/react-native-cameraroll/blob/bc557cf1693ed40b9924e19bd6206255f1dcffcf/ios/RNCCameraRollManager.m#L197

**Comment by scarlac** [comment]
@JoshuaGross I'd be fine with a docs fix.

Current code example in `README.md` do not include this options (see https://github.com/react-native-community/react-native-cameraroll#example). I also see Expo snacks around the web not using this property, so we're almost guaranteed to have people fumbling for answers. If it's truly breaking, I think it deserves a proper mention.

**Comment by BenJeau** [comment]
@JoshuaGross Yep, that fixes my problem! Thanks @scarlac

**Comment by JoshuaGross** [comment]
@scarlac I changed my mind, I think it's worthwhile changing the default in this case, I'll just need to test a lot of things on my end to ensure nothing breaks at FB. Would you mind submitting a PR? Might be worthwhile submitting followup documentation changes to indicate that "all" is the default for that param.

**Comment by scarlac** [comment]
Sounds good! I'll have a look on Monday, @JoshuaGross

**Comment by BenJeau** [comment]
@JoshuaGross and now there are some duplicate (since it returns every album), but when I put the groupName param to filter out the photo to only be from the 'Camera Roll' or 'Recently Added', no images are returned even though when this param is not specified, the images have either the 'Camera Roll' or 'Recently Added' value for group_name

**Comment by JoshuaGross** [comment]
@BenJeau does `SavedPhotos` work any better for you?

**Comment by BenJeau** [comment]
@JoshuaGross when I put `SavedPhotos`, no images are returned, weird

**Comment by JoshuaGross** [comment]
That's unfortunate. We'll need to dig into it more then - I'll see if I can do that Monday as well.

**Comment by BenJeau** [comment]
@JoshuaGross Sounds good, thank you. For now, I'll just filter the data after `CameraRoll.getPhotos()` gets called

**Comment by BenJeau** [comment]
Actually nevermind, the duplication stopped happening after rebuilding the project a couple of times without the `groupName` param and with`groupTypes: 'All'`

**Comment by bartolkaruza** [comment]
@JoshuaGross did you see this commit on the RNC repo (that's not on RN core) ? https://github.com/react-native-community/react-native-cameraroll/commit/0d1059ef75889103382c26e2cc18b32c393943e0

It basically sets all as default on JS side.

**Comment by scarlac** [comment]
@JoshuaGross PR up. Let me know what tweaks you want, if any.

**Comment by vicki15** [comment]
When I try to specify a value for groupTypes (for example All or SavedPhotos) I get this weird error
```
ExceptionsManager.js:82 Invalid PHAssetCollectionSubtype 'savedphotos'. should be one of: (
    albumCloudShared,
    albumMyPhotoStream,
    albumRegular,
    any,
    imported,
    smartAlbumAllHidden,
    smartAlbumBursts,
    smartAlbumDepthEffect,
    smartAlbumFavorites,
    smartAlbumGeneric,
    smartAlbumLivePhotos,
    smartAlbumPanoramas,
    smartAlbumRecentlyAdded,
    smartAlbumScreenshots,
    smartAlbumSelfPortraits,
    smartAlbumSlomoVideos,
    smartAlbumTimelapses,
    smartAlbumUserLibrary,
    smartAlbumVideos,
    syncedAlbum,
    syncedEvent,
    syncedFaces
)
```

But If I try instead to specify one of the enums from the error such as 'Any' I get

```
ExceptionsManager.js:82 Warning: Failed params type: Invalid params `groupTypes` of value `any` supplied to `CameraRoll.getPhotos`, expected one of ["Album","All","Event","Faces","Library","PhotoStream","SavedPhotos"].
Bad object: {
  "first": 1,
  "assetType": "Photos",
  "groupTypes": "any"
}
```

Since I am not able to set groupTypes, I am getting back an empty array :/

Here is my code

```
    loadLatestImage = () => {
        CameraRoll.getPhotos({
            first: 1,
            assetType: 'Photos',
            groupTypes: 'any'
        }).then(r => {
            if (r.length > 0) {
                console.log('loaded image');
                this.setState({latestImage: r.edges[0]});
            } else {
                console.log('User does not have photos');
            }
        }).catch((err) => {
            console.log('Error loading latest image ' + err);
        });
    }
```

And I am using "react-native": "0.59.8". Any ideas?

**Comment by vicki15** [comment]
@JoshuaGross

**Comment by dev2612** [comment]
I am facing a problem with videos specifically. In my scenario, I have to save a file on cameraRoll and pick the last saved file from the camera roll to share it further. 

iOS cameraRoll retains the video's original metadata and thus save the file with createdate and not with today's Date. 

So when I pick the last saved file, I get someother file instead of the video I just saved to cameraRoll

Any help in this regards will be highly appreciable. it is bit Urgent. Thanks in advance.
