### ISSUE TITLE
Getting permission denied error on Android after I have inlcuded permissions in AndroidManifest.xml

### ISSUE THREAD

**Issue by ethanyuwang** [react-native-community/react-native-cameraroll#19]
I have already included the following permissions in my `AndroidManifest.xml`:

```
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

However after I call `CameraRoll.saveToCameraRoll(Platform.OS === 'ios' ? this.props.imageItem.url : this.state.imageUri);` I'm still getting the following permission error:
```

03-28 15:50:22.567 13354 13395 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
03-28 15:50:22.567 13354 13395 W ReactNativeJS: Error: Permission denied
03-28 15:50:22.567 13354 13395 W ReactNativeJS: createErrorFromErrorData@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2012:26
03-28 15:50:22.567 13354 13395 W ReactNativeJS: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:1964:51
03-28 15:50:22.567 13354 13395 W ReactNativeJS: __invokeCallback@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2531:23
03-28 15:50:22.567 13354 13395 W ReactNativeJS: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2262:34
03-28 15:50:22.567 13354 13395 W ReactNativeJS: __guard@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2435:15
03-28 15:50:22.567 13354 13395 W ReactNativeJS: invokeCallbackAndReturnFlushedQueue@http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:2261:21
03-28 15:50:22.567 13354 13395 W ReactNativeJS: invokeCallbackAndReturnFlushedQueue@[native code]
```

**Comment by joseguerrerov** [comment]
@ethanyuwang the thing is that you have to explicitly ask for the permission. Adding them to the manifest is just a way to list all the permission you're going to be asking inside the app.

You can solve this easily with something like this:
```JavaScript
import { PermissionsAndroid, Platform } from 'react-native';
import CameraRoll from '@react-native-community/cameraroll';

const checkAndroidPermission = async () => {
    try {
      const permission = PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE;
      await PermissionsAndroid.request(permission);
      Promise.resolve();
    } catch (error) {
      Promise.reject(error);
    }
};

const savePicture = async () => {
    if (Platform.OS === 'android'){
      await checkAndroidPermission();
    }
   CameraRoll.saveToCameraRoll(tag, [type]);
};
```

Hope it helps 😸

**Comment by joseguerrerov** [comment]
@ethanyuwang also if you can check what the actual error is that could tell you whats wrong.
```JavaScript
import CameraRoll from '@react-native-community/cameraroll';

const savePicture = async () => {
    try {
        await CameraRoll.saveToCameraRoll(tag, [type]);
    } catch (error) {
        //Print the error
        console.log(error);
    }
};

// call savePicture() whenever you need it.

```

**Comment by bartolkaruza** [comment]
@ethanyuwang looks like @joseguerrerov has some great solutions for your issue. I'm closing this issue based on the assumption that you are able to resolve the issue by asking for permissions explicitly, let me know if this is not a case and someone will have a look.

**Comment by souljacker** [comment]
Can we have this on the documentation?

**Comment by souljacker** [comment]
BTW:  I tried this solution and am still getting the error mentioned.

`[23:29:37] E | ReactNativeJS ▶︎ 'An error occurred', { [Error: Could not get media: need READ_EXTERNAL_STORAGE permission]
                             │ framesToPop: 1,
                             │ nativeStackAndroid:
                             │ [ { methodName: 'createException',
                             │ lineNumber: 1953,
                             │ file: 'Parcel.java' },
                             │ { methodName: 'readException',
                             │ lineNumber: 1921,
                             │ file: 'Parcel.java' },
                             │ { methodName: 'readExceptionFromParcel',
                             │ lineNumber: 183,
                             │ file: 'DatabaseUtils.java' },
                             │ { methodName: 'readExceptionFromParcel',
                             │ lineNumber: 135,
                             │ file: 'DatabaseUtils.java' },
                             │ { methodName: 'query',
                             │ lineNumber: 418,
                             │ file: 'ContentProviderNative.java' },
                             │ { methodName: 'query',
                             │ lineNumber: 804,
                             │ file: 'ContentResolver.java' },
                             │ { methodName: 'query',
                             │ lineNumber: 753,
                             │ file: 'ContentResolver.java' },
                             │ { methodName: 'query',
                             │ lineNumber: 711,
                             │ file: 'ContentResolver.java' },
                             │ { methodName: 'doInBackgroundGuarded',
                             │ lineNumber: 324,
                             │ file: 'CameraRollModule.java' },
                             │ { methodName: 'doInBackgroundGuarded',
                             │ lineNumber: 250,
                             │ file: 'CameraRollModule.java' } ],
                             │ userInfo: null,
                             │ code: 'E_UNABLE_TO_LOAD_PERMISSION',
                             │ line: 1730,
                             │ column: 26,
                             └ sourceURL: 'http://localhost:8081/index.bundle?platform=android&dev=true&minify=false' }`

Can someone help me?

**Comment by joseguerrerov** [comment]
Hi @souljacker,
Did you put that permission in the Manifest?
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

It would be a good idea to add that snippet to the readme or probably to the code itself @bartolkaruza WDYT?

**Comment by souljacker** [comment]
> Hi @souljacker,
> Did you put that permission in the Manifest?
> `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
> 
> It would be a good idea to add that snippet to the readme or probably to the code itself @bartolkaruza WDYT?


Yeah, after doing what is described here it worked. It would be nice to have this on the docs, though.

**Comment by mahdidarzi** [comment]
i solve this with
export const isIos = (Platform.OS === 'ios');
 requestStoragePermission = async () => {
    if (Platform.Version < 23 || isIos) {
      return true
    }
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
      );
      return (granted === PermissionsAndroid.RESULTS.GRANTED);
    } catch (err) {
      console.log(err);
    }


  };

**Comment by mahdidarzi** [comment]
i solve this with
export const isIos = (Platform.OS === 'ios');
requestStoragePermission = async () => {
if (Platform.Version < 23 || isIos) {
return true
}
try {
const granted = await PermissionsAndroid.request(
PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
);
return (granted === PermissionsAndroid.RESULTS.GRANTED);
} catch (err) {
console.log(err);
}

};
"dependencies": {
    "@react-native-community/cameraroll": "^1.2.0",
    "jetifier": "^1.6.4",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-permissions": "^2.0.2",
    "react-native-reanimated": "^1.2.0",
    "react-native-view-shot": "^3.0.2",
    "react-navigation": "^3.11.1"
  },

**Comment by kiransawant15** [comment]
> @ethanyuwang the thing is that you have to explicitly ask for the permission. Adding them to the manifest is just a way to list all the permission you're going to be asking inside the app.
> 
> You can solve this easily with something like this:
> 
> ```js
> import { PermissionsAndroid, Platform } from 'react-native';
> import CameraRoll from '@react-native-community/cameraroll';
> 
> const checkAndroidPermission = async () => {
>     try {
>       const permission = PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE;
>       await PermissionsAndroid.request(permission);
>       Promise.resolve();
>     } catch (error) {
>       Promise.reject(error);
>     }
> };
> 
> const savePicture = async () => {
>     if (Platform.OS === 'android'){
>       await checkAndroidPermission();
>     }
>    CameraRoll.saveToCameraRoll(tag, [type]);
> };
> ```
> 
> Hope it helps

When i run following code photo doesn't get saved in gallery all the permissions are set in androidmanifest.xml file

The following code prints promise rejected in console please help

takePicture = async () => {

if (this.camera) {
const options = { quality: 0.5, base64: true };
const data = await this.camera.takePictureAsync(options);
console.log(data.uri);
console.log(CameraRoll.getAlbums);
CameraRoll.saveToCameraRoll(data.uri,"photo").catch(function () {
console.log("Promise Rejected");
});

}
}

Further if i i dont catch the promise and make it like below
CameraRoll.saveToCameraRoll(data.uri,"photo");
it gives me following error external media storage directoyry not avialable

Please not i dont have sd card in my mobile
i am running above code in anrdoid mobile diectly not using an emulator
and i am trying to save captured image in phones gallery directly but not able to do so

**Comment by openwell** [comment]
@joseguerrerov will like to know if the permission function will be required for ios.
Also when I followed your procedure for android... I get something like this in return 
`content://media/external_primary/file/92336`
And I cannot see the image in the android gallery ... will like to know if there is any other thing to do.

**Comment by kiransawant15** [comment]
hi same here i changed above code
added one line for permission 
let permission = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
and it worked but again i am getting same thing content://media/external_primary/file/92336

not able to see this image in gallery i was able to see above file in my phones MyFIle application then under Pictures Folder i was able to see one file named  "Camera" when i rename aoforesaid to Camera.png it becomes an image 
So strange behaviour 
Any help would be appreciated 
hOW TO DIRECTLY SAVE THE CAPTURED IMAGE AS A PNG OR JPEG  please help

**Comment by openwell** [comment]
@kiransawant15 without the camera roll package... can you console.log data.uri from takePictureAsync(), and kindly update us on the output.

**Comment by openwell** [comment]
@kiransawant15 download the lastest react-native camera and retry

https://github.com/react-native-community/react-native-camera/releases/tag/v3.22.1

**Comment by kiransawant15** [comment]
> @joseguerrerov will like to know if the permission function will be required for ios.
> Also when I followed your procedure for android... I get something like this in return
> `content://media/external_primary/file/92336`
> And I cannot see the image in the android gallery ... will like to know if there is any other thing to do.

downloaded new version now it is working properly

**Comment by herysihn918** [comment]
I have the same issue.
I am using react-native-view-shot and @react-native-community/cameraroll to capture the screenshot and save it on the external storage.
But I always get the permission denied error in Android. I have tried all the method above, but the same. Please help me.
Android version is 29.

**Comment by wxingheng** [comment]
@joseguerrerov will like to know if the permission function will be required for ios.
Also when I followed your procedure for android... I get something like this in return
content://media/external_primary/file/92336
And I cannot see the image in the android gallery ... will like to know if there is any other thing to do.

**Comment by bartolkaruza** [comment]
@wxingheng There has been some effort made in documenting how to deal with this in #202 . Those doc changes are not merged yet, but the answer is in that PR.

**Comment by code8decode** [comment]
https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010

**Comment by Piyush132000** [comment]
hlo friends, 


all prmisssions
 <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
given by me and  i also


 const checkAndroidPermission = async () => {
        try {
          const permission = PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE;
          await PermissionsAndroid.request(permission);
          Promise.resolve();
        } catch (error) {
          Promise.reject(error);
        }
    };
    const savePicture = async (uri) => {
        if (Platform.OS === 'android'){
          await checkAndroidPermission();
        }
       CameraRoll.saveToCameraRoll(uri, 'photo');
    };



it does not store ScreenShot in gallery please help if you find answer.

**Comment by alexco2** [comment]
@dmevt this fixed the problem for me, thanks!
