### ISSUE TITLE
Gif uploads lose animation data

### ISSUE THREAD

**Issue by aspectgfg** [react-native-community/react-native-cameraroll#193]
Uploading Gifs from camera roll with `ph:` uri's lose their animation data.

Dug into the code and found the issue is caused by [this commit](https://github.com/react-native-community/react-native-cameraroll/commit/c958493441edf622dbc320b9e1319298b8123481).

There really is no valid reason for the unconfigurable default to be a force conversion into jpeg, especially with todays rich mime landscape. If backwards compat was an issue, then the library should have issued a major version change.

**Comment by bartolkaruza** [comment]
Not sure if it's an exact duplicate, but it looks related to https://github.com/react-native-community/react-native-cameraroll/issues/16

**Comment by Mavenic** [comment]
Any solution or workaround ?

**Comment by aspectgfg** [comment]
@Mavenic I had to use patch package and undo the commit. All you have to do is delete those lines.
https://www.npmjs.com/package/patch-package Patch package if you need.

**Comment by bartolkaruza** [comment]
I found the time to look into this in more detail and @aspectgfg you are completely right, that commit overrides the mime type completely. I propose we revert this commit in a major version, which solves the problem for you guys and keeps whoever is relying on jpeg from breaking. Then we can add a configurable feature to override mime type in a minor version following that.

**Comment by bartolkaruza** [comment]
Looping in @maxaggedon for a heads up that the next major version will no longer default to JPEG on upload

**Comment by maxaggedon** [comment]
@bartolkaruza duly noted, thanks for the heads up !

**Comment by Mavenic** [comment]
@aspectgfg Thanks for the update, but it's still not working on ios

**Comment by bartolkaruza** [comment]
@Mavenic this issue is particularly about uploading. So if a GIF is already present on the device, then uploaded, the code that was reverted forces that image to be a JPEG, losing it's mime type and the GIF related data. The saving issue is separate and tracked in #16
