### ISSUE TITLE
Document Android request permissions

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/react-native-cameraroll#194]
This issue is made to keep track of adding the request for permissions that is needed on Android 29 to the documentation. The workaround mentioned on #19 describes in more detail what is required.

https://github.com/react-native-community/react-native-cameraroll/issues/19

**Comment by kiranjd** [comment]
I would like to take this up

**Comment by kiranjd** [comment]
#201 PR resolves this @bartolkaruza

**Comment by bartolkaruza** [comment]
This is now fixed on master
