### ISSUE TITLE
Filtering by album title doesn't work on iOS

### ISSUE THREAD

**Issue by EliSadaka** [react-native-community/react-native-cameraroll#197]
# Bug report

## Summary

On iOS, filtering by album title using the `groupName` param doesn't work. Instead, it still returns results from all albums. The same code works correctly on Android.

## Environment info

`react-native info` output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.15.5
      CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
      Memory: 5.26 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v10.15.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6
      react-native: ~0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 1.7.2

## Steps to reproduce

1. Add a valid album title to the `groupName` param before passing the params object to the getPhotos method.

Describe what you expected to happen:

1. The results from the getPhotos method are filtered to only contain results from the specified album.

## Reproducible sample code

```js
const params = {
      first: 24,
      assetType: 'All',
      mimeTypes: ['video/quicktime', 'image/png', 'video/mp4', 'image/jpeg'],
      groupName: 'Test',
};
const results = await CameraRoll.getPhotos(params);
```

**Comment by bartolkaruza** [comment]
Looks related to #41

**Comment by pribeh** [comment]
@bartolkaruza it appears to be a duplicate. Just to note, looks like our issue is resolved by specifying groupTypes: 'Album' when retrieving album photos as per @ZephyrFang's suggestion here:

https://github.com/react-native-community/react-native-cameraroll/issues/41#issuecomment-525970834

**Comment by bartolkaruza** [comment]
Ok, closing as duplicate for now. Let me know if there is specific case not covered by #41 and I'll reopen.
