### ISSUE TITLE
ALAssetsLibrary URIs crash on certain devices

### ISSUE THREAD

**Issue by airlaser** [react-native-community/react-native-cameraroll#20]
Still working to determine if it's model or device specific. 

Using react's default `Image` tag, providing a URI crashes the app (causes an exception at the obj-c side, not a JS crash). The same code works fine on other devices. 

On these devices the images simply do not display unless `CameraRoll` is installed. After `CameraRoll` is installed the images display, then the app immediately freezes as obj-c side of code crashes. This is different than using a `PHAsset` (`photos://uuid`) URI, which gives a JS exception about finding a loader for the URL. 

This is with 0.59. Noticing it on an upgrade from 0.56.

**Comment by skyforeverGE** [comment]
Right now, based on API getPhotos, the uri is kind of 'ph://', which cannot be handled by most of 3rd party fetch-blob lib, always give me something like 'the file doesn't exist' or 'there is no such file'; there only have content-type info but no size, filename, ... (other info) even though using the js fetch. anyone has any idea or solution about it? 
(P.S: For example, need react-native-fetch-blob to copy file from camera roll to the path under application package.)
