### ISSUE TITLE
No image getPhotos with after parameter in Ios

### ISSUE THREAD

**Issue by mbDilepix** [react-native-community/react-native-cameraroll#221]
Hello, I try to select image with the follow code, but it work only with android :+1: 

let listPictures = await CameraRoll.getPhotos({
      first: 100,
      after: "100",
      assetType: 'Photos',
      groupTypes : 'All'
    })

In ios listPictures is empty. Do you know where it come from ?

**Comment by leonardomdr** [comment]
Hey, I'm with the same issue here. What you have done?
