### ISSUE TITLE
CameraRoll .save failed with `Permission denied` error on Android

### ISSUE THREAD

**Issue by MichalAsh58** [react-native-community/react-native-cameraroll#222]
I'm having the same problem. I have permission for writing in storage and yet- while running "CameraRoll.save(data.uri)" I get an error- Permission denied.
Would like to get your help with that issue.

my code:

    import React, {PureComponent} from 'react';
    import {
      StyleSheet,
      Text,
      TouchableOpacity,
      View,
      PermissionsAndroid,
    } from 'react-native';
    import {RNCamera} from 'react-native-camera';
    import CameraRoll from '@react-native-community/cameraroll';
    
    const requestCameraPermission = async () => {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.CAMERA,
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.log('You can use the camera');
        } else {
          console.log('Camera permission denied');
        }
      } catch (err) {
        console.warn(err);
      }
    };
    
    const requestCameraPermissionWrite = async () => {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.log('You can write to storage');
        } else {
          console.log('Camera permission denied');
        }
      } catch (err) {
        console.warn(err);
      }
    };
    
    class CameraScreen extends PureComponent {
      render() {
        return (
            <RNCamera
              ref={(ref) => {
                this.camera = ref;
              }}
              type={RNCamera.Constants.Type.back}
              captureAudio={false}
            />
            <View>
              <TouchableOpacity
                onPress={() => {
                  requestCameraPermission();
                  requestCameraPermissionWrite();
                  this.takePicture();
                }}
                // onPress={}
                <Text style={{fontSize: 14}}> SNAP </Text>
              </TouchableOpacity>
            </View>
          </View>
        );
      }
    
      takePicture = async () => {
        if (this.camera) {
          const options = {quality: 1, base64: true};
          const data = await this.camera.takePictureAsync(options);
          CameraRoll.save(data.uri).catch((error) => {
            console.log(error);
          });
    
          console.log(data.uri);
        }
      };
    }
    
    
    export default CameraScreen;

When I press "SNAP" I get on my Terminal:

    LOG      You can use the camera
    LOG      You can write to storage
    LOG      file:///data/user/0/com.project2/cache/Camera/3652215d-4e6c-4724-ba0e-a5cf3afd5227.jpg
    LOG      [Error: Permission denied]

**Comment by fabioplaka** [comment]
Same problem to me. Any solution please?

**Comment by mayur-shelar** [comment]
@fabioplaka @MichalAsh58 I too was facing the same issue. [This](https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010) #219 solved the issue for me.

**Comment by MichalAsh58** [comment]
I added "android:requestLegacyExternalStorage="true"" but still getting the same error.
Any other idea?

**Comment by fabioplaka** [comment]
> I added "android:requestLegacyExternalStorage="true"" but still getting the same error.
> Any other idea?

Me too

**Comment by fabioplaka** [comment]
> @fabioplaka @MichalAsh58 I too was facing the same issue. [This](https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010) #219 solved the issue for me.

I tried on emulator and everything works fine, but on device not

**Comment by MichalAsh58** [comment]
> > @fabioplaka @MichalAsh58 I too was facing the same issue. [This](https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010) #219 solved the issue for me.
> 
> Yes it works now, thank you :)

Which API version do you use in your android emulator?
And did the edit of AndroidManifest.xml fixed it all for you?

**Comment by fabioplaka** [comment]
> > > @fabioplaka @MichalAsh58 I too was facing the same issue. [This](https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010) #219 solved the issue for me.
> > 
> > 
> > Yes it works now, thank you :)
> 
> Which API version do you use in your android emulator?
> And did the edit of AndroidManifest.xml fixed it all for you?

Firstly I installed last version of the library. The API version is 29, and I added **android:requestLegacyExternalStorage="true"** at AndroidManifest.xml. 
I think you should try from beginning, delete the app from device or emulator, clean build folder and run again

**Comment by MichalAsh58** [comment]
> > > > @fabioplaka @MichalAsh58 I too was facing the same issue. [This](https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010) #219 solved the issue for me.
> > > 
> > > 
> > > Yes it works now, thank you :)
> > 
> > 
> > Which API version do you use in your android emulator?
> > And did the edit of AndroidManifest.xml fixed it all for you?
> 
> Firstly I installed last version of the library. The API version is 29, and I added **android:requestLegacyExternalStorage="true"** at AndroidManifest.xml.
> I think you should try from beginning, delete the app from device or emulator, clean build folder and run again

thanks. what library do you mean when you say "last version"?

**Comment by fabioplaka** [comment]
> > > > > @fabioplaka @MichalAsh58 I too was facing the same issue. [This](https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010) #219 solved the issue for me.
> > > > 
> > > > 
> > > > Yes it works now, thank you :)
> > > 
> > > 
> > > Which API version do you use in your android emulator?
> > > And did the edit of AndroidManifest.xml fixed it all for you?
> > 
> > 
> > Firstly I installed last version of the library. The API version is 29, and I added **android:requestLegacyExternalStorage="true"** at AndroidManifest.xml.
> > I think you should try from beginning, delete the app from device or emulator, clean build folder and run again
> 
> thanks. what library do you mean when you say "last version"?

https://github.com/react-native-community/react-native-cameraroll

**Comment by Quang-Dong** [comment]
> 
> 
> > > > @fabioplaka @MichalAsh58 I too was facing the same issue. [This](https://github.com/react-native-community/react-native-cameraroll/issues/219#issuecomment-671411010) #219 solved the issue for me.
> > > 
> > > 
> > > Yes it works now, thank you :)
> > 
> > 
> > Which API version do you use in your android emulator?
> > And did the edit of AndroidManifest.xml fixed it all for you?
> 
> Firstly I installed last version of the library. The API version is 29, and I added **android:requestLegacyExternalStorage="true"** at AndroidManifest.xml.
> I think you should try from beginning, delete the app from device or emulator, clean build folder and run again

Thank you, it's work

**Comment by Piyush132000** [comment]
please give me instruction i am also facing same issue and the detail here not relevant  for me  where i need to add android:requestLegacyExternalStorage="true" this line  . I google it but not find relevant answer .
Thanks in advance

**Comment by MarcosVel** [comment]
> I added "android:requestLegacyExternalStorage="true"" but still getting the same error. Any other idea?

Close the app, hold in the icon of your app on menu, go to info, clear the cache and then the storage of the app, then uninstall your app. After this, close the simulator and open with cold boot, after that just hit the command line to run the app again, worked here!
