### ISSUE TITLE
How to get name of image in ios

### ISSUE THREAD

**Issue by mayankmittal242** [react-native-community/react-native-cameraroll#25]
I am  getting file uri which is not acceptable by any other node module which can give me metadata or file name

**Comment by remigijusbalc** [comment]
Go to RCTCameraRollManager.m file in project directory, there add @"name" property, as shown in screenshot
![Screenshot 2019-04-04 at 14 07 32](https://user-images.githubusercontent.com/32093119/55551261-0b614600-56e3-11e9-84d0-2db78a5e0326.png)

**Comment by bartolkaruza** [comment]
This PR will resolve this feature request: https://github.com/react-native-community/react-native-cameraroll/pull/30

**Comment by bartolkaruza** [comment]
Some work has been done to implement this on #30 but we could really use help on finishing that PR (Finish the JS side and implement the same functionality for Android). Let me know if you want to help.

**Comment by bartolkaruza** [comment]
This is still open after #180 (which only implements file size), if someone wants to open a PR for adding the fileName, I'm happy to review.
