### ISSUE TITLE
iOS: Order when request assetType:All is incorrect

### ISSUE THREAD

**Issue by joseguerrerov** [react-native-community/react-native-cameraroll#27]
## 🐛 Bug Report

When calling `CameraRoll.getPhotos()` in iOS with `assetType: 'All'` in the params the returned array is not ordered as if you are calling it with `assetType: 'Photo' // or Video`. When you call the function with assetType: All the assets are ordered with the oldest first. But if you call it with Photo or Video they are ordered with the most recent first (desired one)
### Using `assetType: 'All'`
__order: oldest first__

![All](https://user-images.githubusercontent.com/13242797/55577067-4e69ec00-56d8-11e9-9654-a6f87b26643c.png)
### Using `assetType: 'Photos'`
__order: most recent first__

![Simulator Screen Shot - iPhone XS Max - 2019-04-04 at 12 46 13](https://user-images.githubusercontent.com/13242797/55577213-a9034800-56d8-11e9-8e97-016273db6874.png)

## To Reproduce

1. Create a new react native project (with react-native init)
2. Link the Camera Roll library
3. Add the permission keys in the Info.plist as described here from the [README](https://github.com/react-native-community/react-native-cameraroll#permissions)
4. call `getPhotos` with the following params:

```js
CameraRoll.getPhotos({
    first: 50 // any number
    groupTypes: 'All',
    assetType: 'All',
});
```
5. call `getPhotos` with the following params:

```js
CameraRoll.getPhotos({
    first: 50 // any number
    groupTypes: 'All',
    assetType: 'Photos', // or 'Videos'
});
```
6. Run `react-native run-ios`
7. Compare results 👀 .

## Expected Behavior
I expect that the return array when querying for any kind of assetType (Photo, Video or All) would have the same order. Which is most recent first.

## Environment
 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 99.85 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.2 => 0.59.2
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
      react-native-redux-boilerplate: 0.1.3
      react-native-version: 2.6.6

**Comment by joseguerrerov** [comment]
It seems the __issue__ is here:
https://github.com/react-native-community/react-native-cameraroll/blob/132af3166da29e9236f80da5367ce06b23b00a89/ios/RNCCameraRollManager.m#L64
If the default return is:
```objective-c
PHFetchOptions *const options = [PHFetchOptions new];
return option:
```
then it can be sort here:
https://github.com/react-native-community/react-native-cameraroll/blob/132af3166da29e9236f80da5367ce06b23b00a89/ios/RNCCameraRollManager.m#L204

I've create a __PR__ for this: https://github.com/react-native-community/react-native-cameraroll/pull/28

**Comment by rpss2** [comment]
Hi, @joseguerrerov. Can I get this ImageComposer component? Thanks.

**Comment by joseguerrerov** [comment]
@rpss2 what do you mean with ImageComposer ?

**Comment by rpss2** [comment]
@joseguerrerov, this screen when selected image, where possible edit image, zoom and crop, etc.
