### ISSUE TITLE
getPhotos return old photos and path is wrong

### ISSUE THREAD

**Issue by remigijusbalc** [react-native-community/react-native-cameraroll#36]
**OLD PHOTOS BUG**: On iOS I set assetType "All", because otherwise it returns 2 photos or none and I get old photos first. On previous versions it returned the newest photos. 
**PATH BUG**: I can't get file size based on new uri bucause RNFetchblob returns that file doesn't exist. On previous version everything worked ok

**Comment by joseguerrerov** [comment]
@remigijusbalc can you please share some additional info:

__Output of react-native info__
__Code Samples__

This might be related to this one https://github.com/react-native-community/react-native-cameraroll/pull/28

But it seems the latest release didn't include this.

**Comment by bartolkaruza** [comment]
> But it seems the latest release didn't include this.

You are right, we are migrating this repo to semantic release, so that every merged fix gets out there. It should be done by the end of the week, including every fix since 1.0.3.

**Comment by Abdelrahman-Nabil** [comment]
is this fixed ? i'm still experiencing the same issue. (using expo SDK 33)

**Comment by bartolkaruza** [comment]
That fix is merged in. I'm not sure about the cameraroll version shipped with Expo, but I think they don't use this library anymore in more recent versions. Try upgrading and let me know if this needs to be re-opened.
