### ISSUE TITLE
Failing Android detox tests

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/react-native-cameraroll#4]
The detox test on CI for Android are failing by timeout. There seems to be more going on than the release bundle not being created correctly as fixed by @matt-oakes in https://github.com/react-native-community/react-native-cameraroll/pull/3.

The app is installed correctly by the test command but is not started by the e2e test. The tests timeout because there is no app running.

If the app is started manually on the emulator, it appears to be working without any issues. Behaviour is the same for CI and local, making it easy to reproduce.

Reproduction:
```
yarn test:detox:android:build:release
yarn test:detox:android:test:release
```

Expected:
Build
Start emulator
Start tests
App starts on emulator by Detox 
Tests pass

Actual:
Build
Start emulator
Start tests
~App starts on emulator by Detox~
_Tests fail_

**Comment by matt-oakes** [comment]
I've opened a draft pull request (#6) which starts to address the issues. Please feel free to pick if from where I have left off or I will continue to try when I have time.

**Comment by bartolkaruza** [comment]
I'm going to turn off the Android UI tests in Circle until we resolve this, so that other fixes can make it out to releases in the mean time. This one is on my list which keeps growing at the top :D

**Comment by sxqnicholas96** [comment]
Hi @bartolkaruza, may I know how have you managed to get detox tests up and running on Android emulators in circleci? I've been working on this and did not have much luck

**Comment by bartolkaruza** [comment]
@sxqnicholas96 I didn't yet unfortunately, I'll post here with a solution when we get it to work

**Comment by matt-oakes** [comment]
I've just fixed this on my local machine and pushed the changes into PR #6. CircleCI needs to be configured to run the jobs for my forked PR though to test that it's working there.

**Comment by bartolkaruza** [comment]
just linking, there are still lingering issues: https://github.com/react-native-community/react-native-cameraroll/issues/34
