### ISSUE TITLE
Cannot read property 'getPhotos' of undefined

### ISSUE THREAD

**Issue by Steffi3rd** [react-native-community/react-native-cameraroll#44]
Hi, 

I just installed this package using **Mostly automatic installation**.

I did : 
1 / `yarn add @react-native-community/cameraroll` 
2 / `react-native link @react-native-community/cameraroll`

```
info Linking "@react-native-community/cameraroll" iOS dependency
info iOS module "@react-native-community/cameraroll" has been successfully linked
info Linking "@react-native-community/cameraroll" Android dependency
info Android module "@react-native-community/cameraroll" has been successfully linked
```

3 / In my RN app, I use the sample example 

```

import CameraRoll from '@react-native-community/cameraroll';

const AddKidScreen = ({ navigation, ...props }) => {
  const [photos, setPhotos] = useState([]);
  const _handleButtonPress = () => {
    CameraRoll.getPhotos({
      first: 20,
      assetType: 'Photos'
    })
      .then(r => {
        setPhotos(r.edges);
      })
      .catch(err => {
        //Error Loading Images
      });
  };
   return <TouchableOpacity onPress={() => _handleButtonPress()}>Photos</TouchableOpacity>
}
```
<img width="476" alt="Capture d’écran 2019-04-19 à 14 41 44" src="https://user-images.githubusercontent.com/814410/56424598-46ea3b80-62b1-11e9-9989-c099eae3d201.png">

**Comment by bartolkaruza** [comment]
Hi there, thanks for reporting. I just ran the same commands on a fresh `react-native init` project and the issue is not reproducible. Can you post more details about your xcode project, Podfile (if you have one) and post the output of `react-native info`? 

I suspect some local modification is causing issue with linking, so as a short cut to all of the above, please check if all the steps from manual linking are correctly applied to your project and let us know what was missing.

**Comment by MiLeung** [comment]
After installing and linking, quitting the simulator and running `react-native run-ios` worked for me.

**Comment by tomonakar** [comment]
I had the same Issue.
`react-native link @react-native-community/cameraroll` didn't work for me.
`Manual installation` worked for me.

**Comment by bartolkaruza** [comment]
@MiLeung @tomonakar Could you give me more context about what exactly 'didn't work'? Which part of the manual installation was not in place after the auto linking? What was the output of react-native link?

I'm not able to reproduce still.

**Comment by tomonakar** [comment]
@bartolkaruza 
Manual installation was worked for me.

I'm sorry for the misunderstanding.
My weak point is English...

**Comment by MiLeung** [comment]
I used `react-native link`. I think something wrong was cached.

**Comment by 77xi** [comment]
you should `cd ios && pod install` after auto link and then rebuild
