### ISSUE TITLE
iOS: Sort order unexpected

### ISSUE THREAD

**Issue by scarlac** [react-native-community/react-native-cameraroll#45]
When attempting to request all photos, photos are returned sorted by collection, instead of being a complete list. This makes it difficult to help users pick their most recent photos taken.
Example:
```
RNCCameraRoll.getPhotos({
  first: 20,
  assetType: 'Photos',
  groupTypes: 'All',
})
```
Will return the 20 latest photos as expected, in the simulator. However, on a real device this may or may not return the most recent 20 photos, as it'll sort the Collections by "end date" which will essentially show the album that was last modified, and show all photos from that album regardless of their date.

A javascript workaround is theoretically possible but it would require to fetch *all* photos (e.g. `first: 9999..`) and then sort by `timestamp`, which goes against the purpose of using cursors.

After tinkering with the source, it's clear that the issue arises from first grabbing collections, then assets. Regardless of the `sortDescriptor`, everything will be grouped by collection:
```
    PHFetchResult<PHAssetCollection *> *const assetCollectionFetchResult = [PHAssetCollection fetchAssetCollectionsWithType:collectionType subtype:collectionSubtype options:collectionFetchOptions];
    [assetCollectionFetchResult enumerateObjectsUsingBlock:^(PHAssetCollection * _Nonnull assetCollection, NSUInteger collectionIdx, BOOL * _Nonnull stopCollections) {
      // Enumerate assets within the collection
      PHFetchResult<PHAsset *> *const assetsFetchResult = [PHAsset fetchAssetsInAssetCollection:assetCollection options:assetFetchOptions];
```

**Proposed solution:**
I propose that we add a condition that if `groupTypes` is `"All"`, then we use [`fetchAssetsWithOptions`](https://developer.apple.com/documentation/photokit/phasset/1624783-fetchassetswithoptions?language=objc) instead of enumerating collections. No change required to `sortDescriptor`

**Comment by bartolkaruza** [comment]
Looking at our implementation and the Apple docs I think you are right about the wrong handling of group_type "all"; it should be retrieving assets ungrouped by PHAssetCollection, which it doesn't do right now. Your proposed solution looks like the way to go to me.

@JoshuaGross any input from FB?

**Comment by JoshuaGross** [comment]
That sounds like the right approach to me! I think it will solve a lot of the problems we’ve seen on our end, too.

**Comment by scarlac** [comment]
In case someone stumbles upon this issue, the current workaround I found was to massively over-fetch and sort manually in JS (untested code adapted from own codebase, so please adjust as necessary):
```
RNCCameraRoll.getPhotos({
  first: 2000,
  assetType: 'Photos',
  groupTypes: 'All',
}).then((response) => {
  response.edges.sort((a, b) => b.node.timestamp - a.node.timestamp);
  return response;
}).then(() => {
  // normal image handling here
});
```

I'll see if I can submit a PR today or tomorrow. Otherwise, anyone should feel free to implement this.

**Comment by scarlac** [comment]
@bartolkaruza, @JoshuaGross, let me know what you think 🙈

**Comment by ramon90** [comment]
Thanks scarlac for the workaround.

**Comment by ramon90** [comment]
But this causes it loop around if there is less than 2000 images, also that results in duplicate keys.

**Comment by scarlac** [comment]
@ramon90 it does yes. That’s another bug I chose to omit from here. You’ll need to remove the duplicates as well. Run result through “uniqBy” on the node image url from lodash or similar.

**Comment by EmilScherdin** [comment]
Had some issues with this as well. Seems like this is still broken when trying to get both videos and photos, at least that's what I get. I does work as expected when setting `assetType: 'photos'`. However, I'm not sure what fails when loading the videos as well.

**Comment by dgarciamuria** [comment]
> Had some issues with this as well. Seems like this is still broken when trying to get both videos and photos, at least that's what I get. I does work as expected when setting `assetType: 'photos'`. However, I'm not sure what fails when loading the videos as well.

I'm seeing the same behavior here. Whenever I use `assetType: 'Videos' | 'Photos'` it works fine, the most recent assets are returned, but when using `assetType: 'All'` the oldest are returned first

**Comment by scarlac** [comment]
@dgarciamuria Did you meant to say `groupTypes`? It checks against groupTypes, but not assetType, as far as I recall. If it's `assetType` I don't immediately think it's related to this issue and/or PR.

**Comment by dgarciamuria** [comment]
Yes you are right. I think it's best to open a new issue. (It was related to the comment above mine)

**Comment by xlcrr** [comment]
Coming from expo here

My .getPhotos() in production is working perfectly, but after upgrading SDK from 32 to 34, and React from 16.3.1 to 16.8.3 introduced this breaking change.

**Comment by mickmak-busicat** [comment]
> In case someone stumbles upon this issue, the current workaround I found was to massively over-fetch and sort manually in JS:
> 
> ```
> RNCCameraRoll.getPhotos({
>   first: 2000,
>   assetType: 'Photos',
>   groupTypes: 'All',
> }).then((response) => {
>   response.edges.sort((a, b) => b.node.timestamp - a.node.timestamp);
>   return response;
> }).then((response) => {
>   // normal image handling here
> });
> ```
> 
> I'll see if I can submit a PR today or tomorrow. Otherwise, anyone should feel free to implement this.

This works well only when small amount of photos are in camera roll.
If user have a lot of photos(ie, 10000+) and we dont want to load them all at one time. 
The order of this approach will be a problem again since `first` parameter does not actual get n latest photos from camera roll. The sorting is just try to sort all the result in page 1 which will cause more confuse for users.
Any method that can actual make the `first` parameter works as expected?

**Comment by ErtugrulBEKTIK** [comment]
I have same problem. Is there any update?

**Comment by scarlac** [comment]
> I have same problem. Is there any update?

I think it was fixed, merged, and resolved entirely unless there is a regression.

**Comment by ErtugrulBEKTIK** [comment]
Same issue exist in standard CameraRoll in react-native and I used this one.
After using @react-native-community/cameraroll version issue was fixed.
Sorry about that.

**Comment by k1115** [comment]
@ErtugrulBEKTIK 

Excuse me, could u share the lines of code how to sort photos?
I've not found the solution yet. :pray:
