### ISSUE TITLE
App crashes on iOS for local video uri

### ISSUE THREAD

**Issue by ramon90** [react-native-community/react-native-cameraroll#49]
The uri returned for video is uri for the video's thumbnail not the video itself, and as a result the app freezes/crashes.

**Comment by ramon90** [comment]
A solution that I found is to use react-native-gallery-manager, it returns AVAsset uri for videos instead of unplayable PHAsset uri returned by react-native-cameraroll

**Comment by bartolkaruza** [comment]
Thanks for reporting, we'll have a look!

**Comment by emilemoureau** [comment]
I got the same error! RN 0.59.3 and iOS 12.2!

**Comment by jonathangreco** [comment]
@bartolkaruza Hi,
Did you take a look ? Because PHAsset are just not compatible with any library like RNFS / Fetch BLOB or so, we just can't use this simply. Is it possible to bring back some assets-library path ?

**Comment by bartolkaruza** [comment]
@jonathangreco I'm struggling to find the time to implement bigger changes like that one. In the mean time, have you seen the workaround for #52 here: https://github.com/react-native-community/react-native-cameraroll/issues/52#issuecomment-488601591

I think implementing a conversion by default inside Cameraroll would be the way to go.

**Comment by jonathangreco** [comment]
@bartolkaruza Yes I've implemented it. Sure it works but for how long ? Some people find that not stable, me too.

**Comment by jzyds** [comment]
https://github.com/jzyds/react-native-convert-ph-asset

**Comment by bartolkaruza** [comment]
Closing this, for now, see workarounds above if you experience this issue. We'll look at a better handling of the ph url's in one go, hopefully soon.
