### ISSUE TITLE
iOS: Not returning all photos...

### ISSUE THREAD

**Issue by dbarner1** [react-native-community/react-native-cameraroll#5]
Hi guys,
 
I'm finding CameraRoll only returns 142 of 483 photos on my device, when running a simple:

```
    CameraRoll.getPhotos({
      first: 2000,
      assetType: 'Photos',
    })
```

Some facts about my dev setup:
- I'm on RN .57.8.
- The app setup appears correct, as at least some photos return.
- I don't use iCloud, or any cloud solution.
- WhatsApp pictures show just fine.
- I have no other apps copying pictures to my library.
- I noticed this comment, from RN's CameraRoll, which might be relevant: https://github.com/react-native-community/discussions-and-proposals/issues/64#issuecomment-444933345
- I noticed the RN team said this might be fixed in .59?  Would that then be fixed in this lib?
<img width="790" alt="Screenshot 2019-03-16 14 41 33" src="https://user-images.githubusercontent.com/23145200/54480008-e66f6680-47f9-11e9-81c4-71f3ecf8f959.png">

Thanks to those working/have worked on this repo.  I love the empowerment it gives us to control the

 camera picker UX.

Dave

**Comment by dbarner1** [comment]
I think it was done here?
https://github.com/facebook/react-native/commit/8ce9b476262e4b8d9fb3c44b759e1e6e248eb95c

**Comment by dbarner1** [comment]
Also, seems to only return photos when testing on a real device?  This wasn't the case with RN's Camera Roll.  Just wanted to make sure.

**Comment by bartolkaruza** [comment]
Thanks for reporting! We're syncing up any changes that happen on RN Core to this library, so the fix you mention will be manually synched over (by me, as soon as I get around to it). I'll update this issue as soon as that is done and a new release of cameraroll is published.

>Also, seems to only return photos when testing on a real device? This wasn't the case with RN's Camera Roll. Just wanted to make sure.

All functionality should be the same between the old React Native cameraroll and the new library. If you still experience this issue, could you open it as a separate issue report on this repository? Thanks.

**Comment by dbarner1** [comment]
Thanks @bartolkaruza! Looking forward to it. Thanks for the work here!

**Comment by joseguerrerov** [comment]
@dbarner1 this work for me:
```
CameraRoll.getPhotos({
    first: 10,
     assetType: 'All',
      groupTypes: 'All',
 });
```
But I couldn't found a way to play videos from the camera roll ? any idea @bartolkaruza

**Comment by dbarner1** [comment]
@joseguerrerov That's not what I'm after here.  

Basically, agreed, the call works, but the call isn't returning *all* images on my device.

Say you have 400 images on your device, and you call with first: 2000, it isn't returning all 400 for me.

**Comment by bartolkaruza** [comment]
> But I couldn't found a way to play videos from the camera roll ? any idea @bartolkaruza

@joseguerrerov https://github.com/react-native-community/react-native-cameraroll/issues/15 could be related to what you are facing

@dbarner1 could this issue be related to the 'SavedPhotos' default as mentioned in this [issue](https://github.com/react-native-community/react-native-cameraroll/issues/18) and fixed by this [pr](https://github.com/react-native-community/react-native-cameraroll/pull/24) ?

**Comment by dbarner1** [comment]
@bartolkaruza This likely fixes it! Will likely have time to confirm this in the coming weeks, but feel free to close this issue in the meantime.  I'll open if still an issue in the future, if works.

@scarlac cheers on the fix!

**Comment by scarlac** [comment]
Does seem like the issue yes. Original report said no photos returned. But you may get a limited amount of photos instead. I think it’s fair to say this is a dupe and is fixed by now, to be released.

**Comment by bartolkaruza** [comment]
I think this should now be resolve in 1.0.4. Could you check @dbarner1 and close if it is fixed please?

**Comment by bartolkaruza** [comment]
closing as fixed, just comment if this is still an issue and reopen.
