### ISSUE TITLE
ANDROID: GetPhotos doesn't work because of groupTypes

### ISSUE THREAD

**Issue by JulienUsson** [react-native-community/react-native-cameraroll#56]
Hello,

The lib doesn't work on Android because GroupType default value is set here in JS https://github.com/react-native-community/react-native-cameraroll/blob/1e37b294269eeb7175a9d952619fb22c4d70821d/js/CameraRoll.js#L167
but in Android if there is the groupType params a exception is thrown 
https://github.com/react-native-community/react-native-cameraroll/blob/1e37b294269eeb7175a9d952619fb22c4d70821d/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java#L220

The bug appears when i upgrade from 1.0.3 to 1.0.4.

I can make a PR to resolve this issue if you want. That is the best solution? ignore the groupType in Android? or something else?

**Comment by bartolkaruza** [comment]
Hi thanks for reporting, I'm trying to reproduce on my side. For some reason it is not yet happening on the tester project and I'm looking into why this is.

**Comment by bartolkaruza** [comment]
@JulienUsson I would have welcomed your PR (and will very much welcome them in the future). I needed to figure out how this bug entered the release in the first place, as it should have failed in one of tests before making it to npm. Feel free to comment on #57 for now.
