### ISSUE TITLE
deletePhotos() incompatible with getPhotos

### ISSUE THREAD

**Issue by scarlac** [react-native-community/react-native-cameraroll#59]
**Summary**
The semi-undocumented iOS-only function `deletePhotos()` uses the old ALAsset API. Using the function per code specification will cause no errors **and** will not actually delete the photos.
`deletePhotos()` expects `assets-library://` URIs but `getPhotos` produces `ph://` URIs.

**Example:**
```
import RNCCameraRoll from '@react-native-community/cameraroll';
// ...
(async () => {
  console.log('result', await RNCCameraRoll.deletePhotos(['ph://8ACFD861-283C-4B3B-9101-3F7F10C10067/L0/001']));
})();
// output: result true
```
This code will always succeed and resolve with `true` even on other devices than mine. However iOS will never prompt the user that app is about to delete photos and it will never actually delete any. After debugging it was clear that we're using `[PHAsset fetchAssetsWithALAssetURLs:assets_ options:nil];` which refers to the old "ALAsset" API which has been officially deprecated.

**Solution**
I think it's fairly easy to solve by switching to `fetchAssetsWithLocalIdentifiers:options:` instead, but I'm unsure if that would work with a URL. If it does not, we should find another solution.

**Why should we fix this**
No other up-to-date library provides this functionality. React Native File System (`react-native-fs`) does not support removal of `ph://` URIs and they said it's out of scope, and `react-native-photos-framework` has not been updated since 2017 (perhaps abandoned).

**Comment by scarlac** [comment]
For the lost souls searching for a workaround:
```js
// iOS: deletePhotos() uses old ALAsset API instead of PHAssets
// so convert new URL to old URL
// (otherwise it won't delete anyting but will resolve just fine)
// Conversion code based on these instructions:
// https://stackoverflow.com/a/28900402
const alAssetUris = photos.map(({ uri }) => {
  const [, localIdentifier] = uri.match('ph://([^/]+)');
  if (!localIdentifier) {
    log(`Unable to find localIdentifier from asset "${uri}"`);
    return uri;
  }
  return `assets-library://asset/asset.JPG?id=${localIdentifier}&ext=JPG`;
});
await RNCCameraRoll.deletePhotos(alAssetUris);
```
where:
```js
const photos = [{ uri: 'ph://8ACFD861-283C-4B3B-9101-3F7F10C10067/L0/001'}];
```

**Comment by bartolkaruza** [comment]
Hi there, thanks for reporting this! Your rationale for pushing for a fix for this makes sense to me and I think cameraroll should support this functionality, but considering deletePhotos is not currently working/documented (or before this issue known to me 😊 ) we should tackle it as a new feature request. I'm very interested in reviewing and helping with a PR for the above!

**Comment by scarlac** [comment]
@bartolkaruza Sounds fair 👍  I'll start working on a fix when I get some time.
If anyone should happen to stumble upon this ticket meanwhile, ping me to see if I've made progress.

**Comment by thekevinbrown** [comment]
Hey @scarlac, have you made progress on this? I have a need for this, so if not I'm happy to take this on.

**Comment by scarlac** [comment]
@thekevinbrown I haven’t gotten started yet. Please go ahead! :)

**Comment by thekevinbrown** [comment]
@scarlac Alrighty, I'll have a go at making a PR for this.

**Comment by thekevinbrown** [comment]
@scarlac please give the code in #69 a go if you get a chance and let me know if you have any feedback.
