### ISSUE TITLE
Latest release failed on xcode

### ISSUE THREAD

**Issue by JordanProtin** [react-native-community/react-native-cameraroll#62]
# Bug

Release v1.1.0 failed when I want to build my app on xcode 

Xcode info output:

<img width="277" alt="Capture d’écran 2019-06-13 à 15 54 28" src="https://user-images.githubusercontent.com/35328504/59442622-d9fba980-8dfa-11e9-965f-114eef94a277.png">

## Environment info

xcode v10.2.1
react-native v0.57.7

**Comment by tylergaw** [comment]
Just installed `1.1.0` and ran into the same error on build. The use of `RCTNetworkingPHUploadHackScheme` was added as a fix in https://github.com/react-native-community/react-native-cameraroll/pull/58

### Environment info
- xcode 10.2.1
- react-native 0.59.5

**Comment by tylergaw** [comment]
Dug in a bit further here. `RCTNetworkingPHUploadHackScheme` is in `master` but looks like it is only available in `0.60` releases of `react-native`.

It was added in this commit:
https://github.com/facebook/react-native/commit/458e70c79d3e12b5ad017d17ccea2fd62c1c3781

That means it's not available in the latest stable release `0.59.9` Here's RCTNetworking in that version of RN https://github.com/facebook/react-native/blob/43945c114eabaa46bd7ec91f5e241f18e1004f2f/Libraries/Network/RCTNetworking.h

That sound right @bartolkaruza?

**Comment by bartolkaruza** [comment]
Sorry about this guys, I've fixed this by moving the string constant to a local variable in this [pr](#63). This makes that particular change independent of RN version. Let me know if something is still not working; the detail level of info provided in this issue made it easy for me to provide the fix quickly.

**Comment by tylergaw** [comment]
Awesome, thank you @bartolkaruza I'll give this version a try soon
