### ISSUE TITLE
Support the save of images to an album

### ISSUE THREAD

**Issue by reyalpsirc** [react-native-community/react-native-cameraroll#65]
# Feature Request

Add possibility to save an image to a specific album on Camera Roll

## Why it is needed

Since there's a possibility to retrieve the pictures of an user in an Album, it should also be possible to save the images to an Album

## Possible implementation

I don't know much about native code in relation to Camera Roll/Gallery

### Code sample

In my opinion, the current `CameraRoll.saveToCameraRoll(tag, [type])` should be traded with `CameraRoll.saveToCameraRoll(tag, [{type, album: 'My Album'}])`

**Comment by reyalpsirc** [comment]
Okay, this seems linked to [pull #55](https://github.com/react-native-community/react-native-cameraroll/pull/55), which solves it with a call to `CameraRoll.save(tag, [{type, album: 'My Album'}])`

**Comment by daksh23** [comment]
> Okay, this seems linked to [pull #55](https://github.com/react-native-community/react-native-cameraroll/pull/55), which solves it with a call to `CameraRoll.save(tag, [{type, album: 'My Album'}])`

but what is the meaning if type can we write type as photo or iamge or only type
