### ISSUE TITLE
Conflict with Autolink (react-native 0.60.0)

### ISSUE THREAD

**Issue by hyun04p** [react-native-community/react-native-cameraroll#68]
# Bug

the library works well on android. However, it doesn't do the same on ios and emits following error: 

null is not an object (evaluating '_nativeInterface.default.getPhotos')

getPhotos
    CameraRoll.js:177:25
_handleButtonPress
    LocalGallery.js:107:25
...

I suspected that the library is not properly linked and tried linking manually in xCode and by react-native link command. However, react-native 0.60.0 does not allow manual linking. 

Following is a part of error message received white building the application with react-native run-ios
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.14.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 19.32 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    npm: 6.10.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

## Reproducible sample code

export class lgdetail extends Component {

  constructor(props) {
    super(props);
    this.state = {
      photos: []
    }

    requestExternalStoragePermission = async () => {
      alert("permission")
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          {
            title: 'My App Storage Permission',
            message: 'My App needs access to your storage ' +
              'so you can save your photos',
          },
        );
        alert("perm suc")
        return granted;
      } catch (err) {
        alert("perm failed")
        console.error('Failed to request permission ', err);
        return null;
      }
    };
    if(Platform.OS === "android" ) {
      requestExternalStoragePermission();
    }
    
  }

  _handleButtonPress = () => {
    alert("loadings")
    CameraRoll.getPhotos({
      first: 20,
      assetType: 'Photos',
    })
      .then(r => {
        this.setState({ photos: r.edges });
        alert(JSON.stringify(r))
      })
      .catch((err) => {
        alert(JSON.stringify(this.state.photos))
        console.log(JSON.stringify(err))
        //Error Loading Images
      });
  };

  render() {
    return (
      <View style={detsty.container}>
        <View>
          
          <ScrollView>
            {this.state.photos.map((p, i) => {
              return (
                <Image
                  key={i}
                  style={{
                    width: 300,
                    height: 100,
                  }}
                  source={{ uri: p.node.image.uri }}
                />
              );
            })}
          </ScrollView>
          <Button title="Load Images" onPress={this._handleButtonPress} />
        </View>
      </View>
    );
  }
}

**Comment by Bartson** [comment]
When can we expect fix?

**Comment by hyun04p** [comment]
It's working after creating a new react-native init project and copy pasting all my code. 
I couldn't figure out why such error occured though.

**Comment by Bartson** [comment]
Really I need to create the entire project? After this, you skipped manual linking, right?

**Comment by Vieriksson** [comment]
I am getting the same error message, even with a fresh react-native-project. 

@hyun04p Did you use react-native link, manual linking or auto linking?

**Comment by hyun04p** [comment]
I ended up downgrading to 0.59.9 because of some NON react-native-community dependencies.
On 0.59.9 everything's working well after 'react-native-link".

But as I mentioned earlier cameraroll worked after refreshing the project even with 0.60.x as well WITHOUT react-native-link.

I couldn't figure out why it wasn't working at the first place tho..

U could probably try clearing all dependency by

rm -rf node_modules
npm install

**Comment by boozi2** [comment]
getting the same error, any updates/fixes ?

**Comment by bartolkaruza** [comment]
I will look into this over the weekend and try to resolve it. Sorry for the wait

**Comment by thymikee** [comment]
Can you update the `@react-native-community/cameraroll` version to 1.2.1 and run `pod install` in `ios` directory? That should help

**Comment by bruno-trindade** [comment]
I am also getting this error, except on Android.  I've tried upgrading to 1.2.1 with no success.  RN 0.59.5

**Comment by thymikee** [comment]
@bruno-trindade we're talking about RN 0.60, your problem is likely different. Please upgrade to 0.60 or create a separate issue with detailed reproduction steps and example repo

**Comment by Bartson** [comment]
Still not working :/ 
RN 0.6 and @react-native-community/cameraroll 1.2.1
Maybe I'm missing something with permissions? App doesn't ask me for access to the photo library. I've entered Privacy - Photo Library Usage Description key into info.plist.

**Comment by Vieriksson** [comment]
@thymikee Upgrading to 1.2.1 and running pod install in the ios-folder worked for me. Thank you!

**Comment by Bartson** [comment]
@thymikee 
My bad (I had **Privacy - Photo Library Addition Usage Description** key instead **Privacy - Photo Library Usage Description**), everything works great now. Thank you :D

**Comment by bartolkaruza** [comment]
thanks for reporting, this shouldn't be an issue anymore.
