### ISSUE TITLE
Include File Size and other metadata that might be useful in the response object

### ISSUE THREAD

**Issue by fctmolina1135** [react-native-community/react-native-cameraroll#73]
# Feature Request

Include file size and other metadata that might be used by the user.

## Why it is needed

PHAssets is still unsupported by other libraries that can get the metadata of the image (e.g., RNFS, rn-fetch-blob, etc.). Instead of using other libraries to get the file size or other metadata of the image, might as well just include it in the response object of the camera roll.

## Possible implementation

Include a prop that will tell if the user will need the metadata aside from the uri and name of the image, `includeMetadata: true`

**Comment by bartolkaruza** [comment]
There is a start on this already open at https://github.com/react-native-community/react-native-cameraroll/pull/30

If someone has the time to implement this I will be happy to review and guide.

**Comment by safaiyeh** [comment]
Hey @bartolkaruza I would like to take this on.

What is needed for this to be 100% complete?

**Comment by jsellam** [comment]
Hi,
Personaly, I need the mime-type in getPhotos.

Best regards,
Jérémie.

**Comment by vforvasile** [comment]
any updates here? 

Media Size is really important.

**Comment by bartolkaruza** [comment]
Fixed by #180

🎉 This PR is included in version 1.7.0 🎉

The release is available on:

npm package (@latest dist-tag)
GitHub release
Your semantic-release bot 📦🚀
