### ISSUE TITLE
[iOS] getPhotos() returns no data for assetType: 'All' and old data for assetType: 'Photos' 

### ISSUE THREAD

**Issue by Abdelrahman-Nabil** [react-native-community/react-native-cameraroll#79]
# Bug

cameraRoll.getPhotos() returns no data for assetType: 'All' and old data for assetType: 'Photos', it works fine on Android only.

## Environment info
Expo SDK 33.0.0 managed workflow

## Expected Output:
full data of most recent photos/videos from the camera roll

## Reproducible sample code

empty response:
`
CameraRoll.getPhotos({     
first: 40,
			...(this.endCursor && {after: this.endCursor}),
			...(Platform.OS === 'ios' && {groupTypes: 'All'}),
			assetType: 'All',
		}).then(response => {  } )
`

old data:
`
CameraRoll.getPhotos({     
first: 40,
			...(this.endCursor && {after: this.endCursor}),
			...(Platform.OS === 'ios' && {groupTypes: 'All'}),
			assetType: 'Photos',
		}).then(response => {  } )
`

**Comment by brentvatne** [comment]
@Abdelrahman-Nabil - you shouldn't use cameraroll in expo, you should use medialibrary instead: https://docs.expo.io/versions/latest/sdk/media-library/
