### ISSUE TITLE
Get user created albums

### ISSUE THREAD

**Issue by pontusab** [react-native-community/react-native-cameraroll#8]
Is it possible to get a user created albums? Or is it something that this library should support?

Expo has something called media-library: https://docs.expo.io/versions/latest/sdk/media-library/ with `getAlbumsAsync`.

That would be awesome to have.

Thanks!

**Comment by bartolkaruza** [comment]
Hi @pontusab that's not yet possible, but definitely something that is within scope for this module!

**Comment by pontusab** [comment]
@bartolkaruza Agree! I think that expo has a lot of good features in their media library 👍

**Comment by NikhilVerma** [comment]
We can port some code over from https://github.com/pentarex/react-native-gallery-manager which has an api to get the albums.

**Comment by bartolkaruza** [comment]
This should work using 
`
groupType: 'Album', 
groupName: 'album-name'
`

Closing for now, let me know if something is not working with this.
