### ISSUE TITLE
No such file 'ph:// ......'

### ISSUE THREAD

**Issue by CesarRivasP** [react-native-community/react-native-cameraroll#89]
For my part, I solved my problem. This was that the uri was not valid when converting images to base64. I solved it as follows:

let imagePATH = null;
    if(Platform.OS === 'ios'){
      let regex = /:\/\/(.{36})\//i;
      let result = uriPhoto.match(regex);
      let photoPATH = `assets-library://asset/asset.JPG?id=${result[1]}&ext=JPG`;

      const dest = `${RNFS.TemporaryDirectoryPath}${Math.random().toString(36).substring(7)}.jpg`;

      imagePATH = await RNFS.copyAssetsFileIOS(photoPATH, dest, 500, 500, 1.0, 1.0, 'contain');
    }
    else if(Platform.OS === 'android'){
      imagePATH = photo;
    }

    const photoBase64 = await RNFS.readFile(imagePATH, 'base64');

**Comment by bunsha** [comment]
if (Platform.OS === 'ios') {
  let arr = fileUri.split('/')
  const dirs = RNFetchBlob.fs.dirs
  filePath = `${dirs.DocumentDir}/${arr[arr.length - 1]}`
} else {
  filePath = audioDataUri
}
