### ISSUE TITLE
React Native cameraRoll save video to device from URL

### ISSUE THREAD

**Issue by morampudibabu** [react-native-community/react-native-cameraroll#91]
Tried with **CameraRoll.saveToCameraRoll(videoURL, 'video')** and also **CameraRoll.save(videoURL, {type: 'Video', album: 'Test'})** but not working

Getting error like **Error: The operation couldn’t be completed. (Cocoa error -1.)**

**Comment by codeoholic** [comment]
While you fetch the file via RNFetchBlob.fetch. Pass appendExt : 'mp4' or 'mov' as config parameter alongside fileCache : true. This should fix your problem.
Also, type:'video' and not 'Video'.

**Comment by bartolkaruza** [comment]
Thanks for the answer @codeoholic . Can you confirm this solved your issue @morampudibabu ? Closing for now.

**Comment by sshmyg** [comment]
I have a bit different error, but same conditions, try to save video file.
`ExceptionsManager.js:44 Error: The operation couldn’t be completed. (PHPhotosErrorDomain error -1.)`
Any suggestions? 
This error occur on ios emulator. On real device promise `CameraRoll.saveToCameraRoll` never resolves.

**Comment by Flouwrian** [comment]
@sshmyg i have the same problem
