### ISSUE TITLE
getPhotos() on Android 10 missing screenshots

### ISSUE THREAD

**Issue by scarlac** [react-native-community/react-native-cameraroll#97]
# Bug

Title is somewhat misleading but is the experience users will get.

**Longer, accurate description:**
New screenshots are sorted last when using `getPhotos()`. The net effect of this, on a device with a lot of photos, is that the user thinks screenshots are not showing at all.

The reason for this seems to be that screenshots taken in Android 10 are no longer tagged with `DATE_TAKEN` but only `DATE_ADDED`. **This change seems to be undocumented**. Since it seems the media library is backed by a sqlite database, it's reasonable to believe that `NULL` values are being sorted last.

I was able to confirm that screenshots were indeed showing, but they were showing as the last items in the gallery. However, prior to upgrading the phone the screenshots would show as expected. After upgrading, old screenshots show in the correct order, however new ones are shown last. This is consistent with the theory that photos are tagged incorrectly at creation.

Given complaints from various support forums, it's possible this is the issue that the FB Messenger team encountered.

## Environment info

React native info output:

```bash
⚡️ react-native info
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-check-app-install: https://github.com/redpandatronicsuk/react-native-check-app-install#readme
  - react-native-orientation: https://github.com/yamill/react-native-orientation#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 503.42 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-custom-components: 1.0.0
```

Library version: 1.2.1

## Steps To Reproduce

1. Take a screenshot
2. Call `getPhotos()`
3. Screenshot appears last in the results

Describe what you expected to happen:

1. Take a screenshot
2. Call `getPhotos()`
3. Screenshot appears first in the results

## Reproducible sample code

Since the issue requires taking screenshots, I cannot build sample code.

However, **I've determined a fix and will submit a PR shortly.**

**Comment by KevinGbalay** [comment]
I've tried your PR. It seems that all images and videos have the wrong timestamp now (0, or Jan 01, 1970). Perhaps changing the logic to check if the image has a timestamp of 0, then call the DATE_ADDED tag. Else, call the DATE_TAKEN tag.

**Comment by scarlac** [comment]
@KevinGbalay This PR should not be modifying the timestamps of the images or videos. Are you talking about sorting or image metadata? The latter is not related to this PR.
